# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import Any, Callable

from transport import BaseClient, Packet
import opcodes as op
import models as m
import packets as p
import polymorphic as pm


class Client(BaseClient):
    """Typed API client."""

    def __init__(self) -> None:
        super().__init__(app_version="26.15.2", build_number=69628)
        self._register_notification_opcodes()

    def _register_notification_opcodes(self) -> None:
        self._notification_opcodes = {
            op.Opcode.EventsNotificationCallAcceptedData,
            op.Opcode.EventsNotificationCallFinishData,
            op.Opcode.EventsNotificationMessageData,
            op.Opcode.EventsTypingData,
            op.Opcode.EventsNotificationMarkData,
            op.Opcode.EventsNotificationContactData,
            op.Opcode.EventsPresenceNotificationMessageData,
            op.Opcode.EventsConfigChangeData,
            op.Opcode.EventsNotificationChatData,
            op.Opcode.EventsNotificationAttachData,
            op.Opcode.IncomingCall,
            op.Opcode.EventsMessagesDeleteRangeData,
            op.Opcode.EventsMessagesDeleteData,
            op.Opcode.Assets,
            op.Opcode.EventsNotificationMessageDelayedData,
            op.Opcode.EventsReactionsChangedData,
            op.Opcode.EventsYouReactedData,
            op.Opcode.EventsNotificationProfiletData,
            op.Opcode.EventsNotificationFoldersData,
            op.Opcode.EventsBannersData,
            op.Opcode.EventsNotificationTranscriptionData,
        }

    async def send_ping_payload(self, req: p.PingPayload) -> None:
        await self.send_raw(1, req.to_dict())

    async def send_log(self, req: p.LogParameters) -> None:
        await self.send_raw(5, req.to_dict())

    async def send_session_init_payload(self, req: p.SessionInitPayload) -> p.SessionInitResponse:
        resp = await self.send_raw(op.Opcode.SessionInit, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_profile(self, req: p.ProfileParameters) -> p.ProfileResponse:
        resp = await self.send_raw(op.Opcode.Profile, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_auth_request(self, req: p.AuthOneMeAuthRequestParameters) -> p.AuthOneMeAuthRequestResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeAuthRequest, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_auth(self, req: p.AuthOneMeAuthParameters) -> p.AuthOneMeAuthResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeAuth, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_login(self, req: p.AuthLoginParameters) -> p.AuthLoginResponse:
        resp = await self.send_raw(op.Opcode.AuthLogin, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty(self, req: p.EmptyParameters) -> None:
        await self.send_raw(20, req.to_dict())

    async def send_config(self, req: p.ConfigParameters) -> p.ConfigResponse:
        resp = await self.send_raw(op.Opcode.Config, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_auth_confirm(self, req: p.AuthOneMeAuthConfirmParameters) -> p.AuthOneMeAuthConfirmResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeAuthConfirm, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty_25(self, req: p.EmptyParameters) -> p.AvatarPresetAvatarResponse:
        resp = await self.send_raw(op.Opcode.AvatarPresetAvatar, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_get_asset_common(self, req: p.AssetsGetAssetCommonParameters) -> p.AssetsGetAssetStickerSetResponse:
        resp = await self.send_raw(op.Opcode.AssetsGetAssetStickerSet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_update(self, req: p.AssetsUpdateParameters) -> p.AssetsUpdateResponse:
        resp = await self.send_raw(op.Opcode.AssetsUpdate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_get_by_ids_common(self, req: p.AssetsGetByIdsCommonParameters) -> p.AssetsGetByIdsAnimojiSetResponse:
        resp = await self.send_raw(op.Opcode.AssetsGetByIdsAnimojiSet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_add(self, req: p.AssetsAddParameters) -> p.AssetsAddResponse:
        resp = await self.send_raw(op.Opcode.AssetsAdd, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_info(self, req: p.ContactContactInfoParameters) -> p.ContactContactInfoResponse:
        resp = await self.send_raw(op.Opcode.ContactContactInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_update(self, req: p.ContactContactUpdateParameters) -> p.ContactContactUpdateResponse:
        resp = await self.send_raw(op.Opcode.ContactContactUpdate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_presence(self, req: p.ContactPresenceParameters) -> p.ContactPresenceResponse:
        resp = await self.send_raw(op.Opcode.ContactPresence, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_list(self, req: p.ContactContactListParameters) -> p.ContactContactListResponse:
        resp = await self.send_raw(op.Opcode.ContactContactList, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_search_contact(self, req: p.SearchContactParameters) -> p.SearchContactResponse:
        resp = await self.send_raw(op.Opcode.SearchContact, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_photos(self, req: p.ContactContactPhotosParameters) -> p.ContactContactPhotosResponse:
        resp = await self.send_raw(op.Opcode.ContactContactPhotos, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_create(self, req: p.ContactContactCreateParameters) -> p.ContactContactCreateResponse:
        resp = await self.send_raw(op.Opcode.ContactContactCreate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_remove_contact_photo(self, req: p.ContactRemoveContactPhotoParameters) -> p.ContactRemoveContactPhotoResponse:
        resp = await self.send_raw(op.Opcode.ContactRemoveContactPhoto, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_contact_contact_by_phone(self, req: p.ContactContactByPhoneParameters) -> p.ContactContactByPhoneResponse:
        resp = await self.send_raw(op.Opcode.ContactContactByPhone, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_info(self, req: p.ChatChatInfoParameters) -> p.ChatChatInfoResponse:
        resp = await self.send_raw(op.Opcode.ChatChatInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_history(self, req: p.ChatChatHistoryParameters) -> p.ChatChatHistoryResponse:
        resp = await self.send_raw(op.Opcode.ChatChatHistory, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_mark(self, req: p.ChatChatMarkParameters) -> p.ChatChatMarkResponse:
        resp = await self.send_raw(op.Opcode.ChatChatMark, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_media(self, req: p.ChatChatMediaParameters) -> p.ChatChatMediaResponse:
        resp = await self.send_raw(op.Opcode.ChatChatMedia, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_delete(self, req: p.ChatChatDeleteParameters) -> None:
        await self.send_raw(52, req.to_dict())

    async def send_chat_chat_list(self, req: p.ChatChatListParameters) -> p.ChatChatListResponse:
        resp = await self.send_raw(op.Opcode.ChatChatList, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_clear(self, req: p.ChatChatClearParameters) -> None:
        await self.send_raw(54, req.to_dict())

    async def send_chat_chat_update(self, req: p.ChatChatUpdateParameters) -> p.ChatChatUpdateResponse:
        resp = await self.send_raw(op.Opcode.ChatChatUpdate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_check_link(self, req: p.ChatCheckLinkParameters) -> p.ChatCheckLinkResponse:
        resp = await self.send_raw(op.Opcode.ChatCheckLink, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_join(self, req: p.ChatJoinParameters) -> p.ChatJoinResponse:
        resp = await self.send_raw(op.Opcode.ChatJoin, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_leave(self, req: p.ChatChatLeaveParameters) -> p.ChatChatLeaveResponse:
        resp = await self.send_raw(op.Opcode.ChatChatLeave, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_members(self, req: p.ChatChatMembersParameters) -> p.ChatChatMembersResponse:
        resp = await self.send_raw(op.Opcode.ChatChatMembers, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_search_public(self, req: p.SearchPublicParameters) -> p.SearchPublicResponse:
        resp = await self.send_raw(op.Opcode.SearchPublic, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_personal_config(self, req: p.ChatPersonalConfigParameters) -> p.ChatPersonalConfigResponse:
        resp = await self.send_raw(op.Opcode.ChatPersonalConfig, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_live_stream_live_stream_info(self, req: p.LiveStreamLiveStreamInfoParameters) -> p.LiveStreamLiveStreamInfoResponse:
        resp = await self.send_raw(op.Opcode.LiveStreamLiveStreamInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_messaging_send(self, req: p.MessagingSendParameters) -> p.MessagingSendResponse:
        resp = await self.send_raw(op.Opcode.MessagingSend, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_typing_send(self, req: p.TypingSendParameters) -> None:
        await self.send_raw(65, req.to_dict())

    async def send_messaging_delete(self, req: p.MessagingDeleteParameters) -> p.MessagingDeleteResponse:
        resp = await self.send_raw(op.Opcode.MessagingDelete, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_messaging_edit(self, req: p.MessagingEditParameters) -> p.MessagingEditResponse:
        resp = await self.send_raw(op.Opcode.MessagingEdit, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_search_chat(self, req: p.SearchChatParameters) -> p.SearchChatResponse:
        resp = await self.send_raw(op.Opcode.SearchChat, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_video_chat_edit(self, req: p.CallsVideoChatEditParameters) -> None:
        await self.send_raw(69, req.to_dict())

    async def send_messaging_msg_get(self, req: p.MessagingMsgGetParameters) -> p.MessagingMsgGetResponse:
        resp = await self.send_raw(op.Opcode.MessagingMsgGet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_search_message_touch(self, req: p.SearchMessageTouchParameters) -> None:
        await self.send_raw(72, req.to_dict())

    async def send_search_message(self, req: p.SearchMessageParameters) -> p.SearchMessageResponse:
        resp = await self.send_raw(op.Opcode.SearchMessage, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_msg_get_stat(self, req: p.ChatMsgGetStatParameters) -> p.ChatMsgGetStatResponse:
        resp = await self.send_raw(op.Opcode.ChatMsgGetStat, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_subscribe(self, req: p.ChatChatSubscribeParameters) -> None:
        await self.send_raw(75, req.to_dict())

    async def send_calls_video_chat_start(self, req: p.CallsVideoChatStartParameters) -> p.CallsVideoChatStartResponse:
        resp = await self.send_raw(op.Opcode.CallsVideoChatStart, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_members_update(self, req: p.ChatChatMembersUpdateParameters) -> p.ChatChatMembersUpdateResponse:
        resp = await self.send_raw(op.Opcode.ChatChatMembersUpdate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_video_chat_start_active(self, req: p.CallsVideoChatStartActiveParameters) -> p.CallsVideoChatStartActiveResponse:
        resp = await self.send_raw(op.Opcode.CallsVideoChatStartActive, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_video_chat_history(self, req: p.CallsVideoChatHistoryParameters) -> p.CallsVideoChatHistoryResponse:
        resp = await self.send_raw(op.Opcode.CallsVideoChatHistory, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_photo_upload(self, req: p.AttachmentsPhotoUploadParameters) -> p.AttachmentsPhotoUploadResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsPhotoUpload, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_video_upload(self, req: p.AttachmentsVideoUploadParameters) -> p.AttachmentsVideoUploadResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsVideoUpload, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_video_play(self, req: p.AttachmentsVideoPlayParameters) -> p.AttachmentsVideoPlayResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsVideoPlay, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_video_chat_create_join_link(self, req: p.CallsVideoChatCreateJoinLinkParameters) -> p.CallsVideoChatCreateJoinLinkResponse:
        resp = await self.send_raw(op.Opcode.CallsVideoChatCreateJoinLink, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_chat_pin_set_visibility(self, req: p.ChatChatPinSetVisibilityParameters) -> p.ChatChatPinSetVisibilityResponse:
        resp = await self.send_raw(op.Opcode.ChatChatPinSetVisibility, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_file_upload(self, req: p.AttachmentsFileUploadParameters) -> p.AttachmentsFileUploadResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsFileUpload, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_file_download(self, req: p.AttachmentsFileDownloadParameters) -> p.AttachmentsFileDownloadResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsFileDownload, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_link_info(self, req: p.LinkInfoParameters) -> p.LinkInfoResponse:
        resp = await self.send_raw(op.Opcode.LinkInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty_96(self, req: p.EmptyParameters) -> p.SessionsInfoResponse:
        resp = await self.send_raw(op.Opcode.SessionsInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty_97(self, req: p.EmptyParameters) -> p.SessionsCloseResponse:
        resp = await self.send_raw(op.Opcode.SessionsClose, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_login_restore_password(self, req: p.AuthOneMeLoginRestorePasswordParameters) -> p.AuthOneMeLoginRestorePasswordResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeLoginRestorePassword, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_details2_fa(self, req: p.AuthOneMeDetails2FAParameters) -> p.AuthOneMeDetails2FAResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeDetails2FA, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_external_callback(self, req: p.ExternalCallbackParameters) -> p.ExternalCallbackResponse:
        resp = await self.send_raw(op.Opcode.ExternalCallback, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_web_app_web_app_request_phone_hash(self, req: p.WebAppWebAppRequestPhoneHashParameters) -> p.WebAppWebAppRequestPhoneHashResponse:
        resp = await self.send_raw(op.Opcode.WebAppWebAppRequestPhoneHash, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_validate_password(self, req: p.AuthOneMeValidatePasswordParameters) -> None:
        await self.send_raw(107, req.to_dict())

    async def send_auth_one_me_validate_hint(self, req: p.AuthOneMeValidateHintParameters) -> None:
        await self.send_raw(108, req.to_dict())

    async def send_auth_one_me_verify_email(self, req: p.AuthOneMeVerifyEmailParameters) -> p.AuthOneMeVerifyEmailResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeVerifyEmail, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_check_email(self, req: p.AuthOneMeCheckEmailParameters) -> p.AuthOneMeCheckEmailResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeCheckEmail, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_set2_fa(self, req: p.AuthOneMeSet2FAParameters) -> None:
        await self.send_raw(111, req.to_dict())

    async def send_auth_one_me_create_track(self, req: p.AuthOneMeCreateTrackParameters) -> p.AuthOneMeCreateTrackResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeCreateTrack, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_check_password(self, req: p.AuthOneMeCheckPasswordParameters) -> p.AuthOneMeCheckPasswordResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeCheckPassword, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_login_check_password(self, req: p.AuthOneMeLoginCheckPasswordParameters) -> p.AuthOneMeLoginCheckPasswordResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeLoginCheckPassword, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_login_profile_delete(self, req: p.AuthOneMeLoginProfileDeleteParameters) -> p.AuthOneMeLoginProfileDeleteResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeLoginProfileDelete, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_messaging_send_callback(self, req: p.MessagingSendCallbackParameters) -> p.MessagingSendCallbackResponse:
        resp = await self.send_raw(op.Opcode.MessagingSendCallback, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_bot_suspend(self, req: p.BotSuspendParameters) -> None:
        await self.send_raw(119, req.to_dict())

    async def send_bot_bot_info(self, req: p.BotBotInfoParameters) -> p.BotBotInfoResponse:
        resp = await self.send_raw(op.Opcode.BotBotInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_calls_token(self, req: p.CallsCallsTokenParameters) -> p.CallsCallsTokenResponse:
        resp = await self.send_raw(op.Opcode.CallsCallsToken, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_web_app_web_app_init_data(self, req: p.WebAppWebAppInitDataParameters) -> p.WebAppWebAppInitDataResponse:
        resp = await self.send_raw(op.Opcode.WebAppWebAppInitData, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_complain(self, req: p.ComplainParameters) -> None:
        await self.send_raw(161, req.to_dict())

    async def send_complain_reasons_get(self, req: p.ComplainReasonsGetParameters) -> p.ComplainReasonsGetResponse:
        resp = await self.send_raw(op.Opcode.ComplainReasonsGet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_calls_video_chat_join(self, req: p.CallsVideoChatJoinParameters) -> p.CallsVideoChatJoinResponse:
        resp = await self.send_raw(op.Opcode.CallsVideoChatJoin, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_msg_react(self, req: p.ReactionsMsgReactParameters) -> p.ReactionsMsgReactResponse:
        resp = await self.send_raw(op.Opcode.ReactionsMsgReact, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_cancel_reaction(self, req: p.ReactionsCancelReactionParameters) -> p.ReactionsCancelReactionResponse:
        resp = await self.send_raw(op.Opcode.ReactionsCancelReaction, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_get_reactions(self, req: p.ReactionsGetReactionsParameters) -> p.ReactionsGetReactionsResponse:
        resp = await self.send_raw(op.Opcode.ReactionsGetReactions, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_get_detailed_reactions(self, req: p.ReactionsGetDetailedReactionsParameters) -> p.ReactionsGetDetailedReactionsResponse:
        resp = await self.send_raw(op.Opcode.ReactionsGetDetailedReactions, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_chat_common_chat_list(self, req: p.ChatCommonChatListParameters) -> p.ChatCommonChatListResponse:
        resp = await self.send_raw(op.Opcode.ChatCommonChatList, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_profile_delete(self, req: p.ProfileDeleteParameters) -> p.ProfileDeleteResponse:
        resp = await self.send_raw(op.Opcode.ProfileDelete, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty_200(self, req: p.EmptyParameters) -> p.GetDeleteTamUserTimeResponse:
        resp = await self.send_raw(op.Opcode.GetDeleteTamUserTime, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_transcribe_media(self, req: p.TranscribeMediaParameters) -> p.TranscribeMediaResponse:
        resp = await self.send_raw(op.Opcode.TranscribeMedia, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_org_info(self, req: p.OrgInfoParameters) -> p.OrgInfoResponse:
        resp = await self.send_raw(op.Opcode.OrgInfo, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_set_chat_reactions(self, req: p.ReactionsSetChatReactionsParameters) -> p.ReactionsSetChatReactionsResponse:
        resp = await self.send_raw(op.Opcode.ReactionsSetChatReactions, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_reactions_get_chat_reactions(self, req: p.ReactionsGetChatReactionsParameters) -> p.ReactionsGetChatReactionsResponse:
        resp = await self.send_raw(op.Opcode.ReactionsGetChatReactions, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_remove(self, req: p.AssetsRemoveParameters) -> p.AssetsRemoveResponse:
        resp = await self.send_raw(op.Opcode.AssetsRemove, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_assets_list_modify(self, req: p.AssetsListModifyParameters) -> p.AssetsListModifyResponse:
        resp = await self.send_raw(op.Opcode.AssetsListModify, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_folders_get(self, req: p.FoldersGetParameters) -> p.FoldersGetResponse:
        resp = await self.send_raw(op.Opcode.FoldersGet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_folders_update(self, req: p.FoldersUpdateParameters) -> p.FoldersUpdateResponse:
        resp = await self.send_raw(op.Opcode.FoldersUpdate, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_folders_reorder(self, req: p.FoldersReorderParameters) -> p.FoldersReorderResponse:
        resp = await self.send_raw(op.Opcode.FoldersReorder, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_folders_delete(self, req: p.FoldersDeleteParameters) -> p.FoldersDeleteResponse:
        resp = await self.send_raw(op.Opcode.FoldersDelete, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_empty_288(self, req: p.EmptyParameters) -> p.AuthOneMeCreateQrResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeCreateQr, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_auth_check(self, req: p.AuthOneMeAuthCheckParameters) -> p.AuthOneMeAuthCheckResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeAuthCheck, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_auth_one_me_auth_by_track(self, req: p.AuthOneMeAuthByTrackParameters) -> p.AuthOneMeAuthByTrackResponse:
        resp = await self.send_raw(op.Opcode.AuthOneMeAuthByTrack, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_suggest_chat_suggest(self, req: p.SuggestChatSuggestParameters) -> p.SuggestChatSuggestResponse:
        resp = await self.send_raw(op.Opcode.SuggestChatSuggest, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_attachments_audio_play(self, req: p.AttachmentsAudioPlayParameters) -> p.AttachmentsAudioPlayResponse:
        resp = await self.send_raw(op.Opcode.AttachmentsAudioPlay, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_banners_banners_get(self, req: p.BannersBannersGetParameters) -> p.BannersBannersGetPayload:
        resp = await self.send_raw(op.Opcode.BannersBannersGet, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_polls_send_vote(self, req: p.PollsSendVoteParameters) -> p.PollsSendVoteResponse:
        resp = await self.send_raw(op.Opcode.PollsSendVote, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_polls_voters_list_by_answer(self, req: p.PollsVotersListByAnswerParameters) -> p.PollsVotersListByAnswerResponse:
        resp = await self.send_raw(op.Opcode.PollsVotersListByAnswer, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    async def send_polls_get_poll_updates(self, req: p.PollsGetPollUpdatesParameters) -> p.PollsGetPollUpdatesResponse:
        resp = await self.send_raw(op.Opcode.PollsGetPollUpdates, req.to_dict())
        return resp.payload  # type: ignore[return-value]

    def on_events_notification_call_accepted_data(self, handler: Callable[[p.EventsNotificationCallAcceptedDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationCallAcceptedData, _wrap)

    def on_events_notification_call_finish_data(self, handler: Callable[[p.EventsNotificationCallFinishDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationCallFinishData, _wrap)

    def on_events_notification_message_data(self, handler: Callable[[p.EventsNotificationMessageDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationMessageData, _wrap)

    def on_events_typing_data(self, handler: Callable[[p.EventsTypingDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsTypingData, _wrap)

    def on_events_notification_mark_data(self, handler: Callable[[p.EventsNotificationMarkDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationMarkData, _wrap)

    def on_events_notification_contact_data(self, handler: Callable[[p.EventsNotificationContactDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationContactData, _wrap)

    def on_events_presence_notification_message_data(self, handler: Callable[[p.EventsPresenceNotificationMessageDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsPresenceNotificationMessageData, _wrap)

    def on_events_config_change_data(self, handler: Callable[[p.EventsConfigChangeDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsConfigChangeData, _wrap)

    def on_events_notification_chat_data(self, handler: Callable[[p.EventsNotificationChatDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationChatData, _wrap)

    def on_events_notification_attach_data(self, handler: Callable[[p.EventsNotificationAttachDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationAttachData, _wrap)

    def on_incoming_call(self, handler: Callable[[p.IncomingCall], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.IncomingCall, _wrap)

    def on_events_messages_delete_range_data(self, handler: Callable[[p.EventsMessagesDeleteRangeDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsMessagesDeleteRangeData, _wrap)

    def on_events_messages_delete_data(self, handler: Callable[[p.EventsMessagesDeleteDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsMessagesDeleteData, _wrap)

    def on_assets(self, handler: Callable[[p.AssetsUpdateContent], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.Assets, _wrap)

    def on_events_notification_message_delayed_data(self, handler: Callable[[p.EventsNotificationMessageDelayedDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationMessageDelayedData, _wrap)

    def on_events_reactions_changed_data(self, handler: Callable[[p.EventsReactionsChangedDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsReactionsChangedData, _wrap)

    def on_events_you_reacted_data(self, handler: Callable[[p.EventsYouReactedDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsYouReactedData, _wrap)

    def on_events_notification_profilet_data(self, handler: Callable[[p.EventsNotificationProfiletDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationProfiletData, _wrap)

    def on_events_notification_folders_data(self, handler: Callable[[p.EventsNotificationFoldersDataResponse], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationFoldersData, _wrap)

    def on_events_banners_data(self, handler: Callable[[p.EventsBannersDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsBannersData, _wrap)

    def on_events_notification_transcription_data(self, handler: Callable[[p.EventsNotificationTranscriptionDataPayload], Any]) -> None:
        def _wrap(pkt: Packet) -> None:
            handler(pkt.payload)  # type: ignore[arg-type]
        self.on(op.Opcode.EventsNotificationTranscriptionData, _wrap)
