# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.crop import Crop
from models.keyboard import Keyboard
from models.log_search_event_params_counters import LogSearchEventParamsCounters
from models.log_search_event_params_sections import LogSearchEventParamsSections
from models.message import Message
from models.photo_attachment import PhotoAttachment
from models.poll_answer import PollAnswer
from models.poll_state import PollState
from models.poll_state_results import PollStateResults
from models.reply_button import ReplyButton
from models.video_collage import VideoCollage
from models.widget_content import WidgetContent

from typing import TypedDict, Any

ContactAttachment = TypedDict(
    "ContactAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "contactId": int | None,
    "firstName": str,
    "lastName": str | None,
    "photoUrl": str | None,
    "phone": str | None,
    "vcfBody": str | None,
    },
    total=False,
)

AudioAttachment = TypedDict(
    "AudioAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "audioId": int,
    "url": str | None,
    "duration": int,
    "wave": list[int] | None,
    "transcription": str | None,
    "transcriptionStatus": str | None,
    "token": str | None,
    },
    total=False,
)

OutgoingContactAttachment = TypedDict(
    "OutgoingContactAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "contactId": int,
    },
    total=False,
)

OutgoingFileAttachment = TypedDict(
    "OutgoingFileAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "token": str | None,
    },
    total=False,
)

UnsupportedAttachment = TypedDict(
    "UnsupportedAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "AttachmentConverter": float | None,
    },
    total=False,
)

StickerAttachment = TypedDict(
    "StickerAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "stickerId": int,
    "width": int,
    "height": int,
    "updateTime": int | None,
    "tags": list[str] | None,
    "url": str,
    "mp4Url": str | None,
    "videoUrl": str | None,
    "firstUrl": str | None,
    "previewUrl": str | None,
    "lottieUrl": str | None,
    "replies": list[int] | None,
    "setId": int | None,
    "authorType": str | None,
    "stickerType": str | None,
    "audio": bool | None,
    },
    total=False,
)

OutgoingShareAttachment = TypedDict(
    "OutgoingShareAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "shareId": int,
    "url": str,
    },
    total=False,
)

LogLogEventParams = TypedDict(
    "LogLogEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    "msg": str,
    "details": str | None,
    },
    total=False,
)

CallAttachment = TypedDict(
    "CallAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "conversationId": str,
    "callType": str,
    "hangupType": str | None,
    "duration": int | None,
    "contactIds": list[int] | None,
    "joinLink": str | None,
    },
    total=False,
)

LogNavEventParams = TypedDict(
    "LogNavEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    "action_id": int,
    "screen_to": int,
    "prev_time": int | None,
    "screen_from": int | None,
    "pip": int | None,
    "reason": int | None,
    "source_id": int | None,
    "source_type": int | None,
    },
    total=False,
)

OutgoingControlAttachment = TypedDict(
    "OutgoingControlAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "event": str,
    "chatType": str | None,
    "title": str | None,
    "userIds": list[int] | None,
    "startPayload": str | None,
    },
    total=False,
)

LogEventParams = TypedDict(
    "LogEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    },
    total=False,
)

OutgoingVideoAttachment = TypedDict(
    "OutgoingVideoAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "token": str | None,
    "duration": int | None,
    "wave": list[int] | None,
    "thumbhash": list[int] | None,
    },
    total=False,
)

FileAttachment = TypedDict(
    "FileAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "fileId": int,
    "token": str,
    "size": int,
    "name": str,
    "preview": dict | None,
    },
    total=False,
)

PollAttachment = TypedDict(
    "PollAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "pollId": int,
    "title": str,
    "answers": list[PollAnswer],
    "settings": int,
    "state": PollState,
    "total": int,
    "result": list[PollStateResults] | None,
    "voterPreviewIds": list[int] | None,
    "version": int | None,
    },
    total=False,
)

AppAttachment = TypedDict(
    "AppAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "appId": int,
    "name": str,
    "icon": str | None,
    "message": str | None,
    "state": int | None,
    "timeout": int | None,
    },
    total=False,
)

InlineKeyboardAttachment = TypedDict(
    "InlineKeyboardAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "callbackId": str,
    "keyboard": Keyboard,
    },
    total=False,
)

OutgoingStickerAttachment = TypedDict(
    "OutgoingStickerAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "stickerId": int,
    },
    total=False,
)

PhotoAttachment = TypedDict(
    "PhotoAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "photoId": int | None,
    "url": str | None,
    "baseUrl": str | None,
    "width": int | None,
    "height": int | None,
    "gif": bool | None,
    "previewData": list[int] | None,
    "mp4Url": str | None,
    "photoToken": str | None,
    "sensitive": bool | None,
    },
    total=False,
)

OutgoingAudioAttachment = TypedDict(
    "OutgoingAudioAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "token": str | None,
    "duration": int | None,
    "wave": list[int] | None,
    },
    total=False,
)

WidgetAttachment = TypedDict(
    "WidgetAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "message": list[WidgetContent],
    },
    total=False,
)

LogSearchEventParams = TypedDict(
    "LogSearchEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    "inputQuery": str,
    "sections": LogSearchEventParamsSections,
    "counters": LogSearchEventParamsCounters,
    },
    total=False,
)

ShareAttachment = TypedDict(
    "ShareAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "shareId": int,
    "url": str | None,
    "title": str | None,
    "description": str | None,
    "host": str | None,
    "image": PhotoAttachment | None,
    "media": dict | None,
    "isSensitive": bool | None,
    },
    total=False,
)

VideoAttachment = TypedDict(
    "VideoAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "videoId": int | None,
    "videoType": int | None,
    "duration": int | None,
    "thumbnail": str | None,
    "width": int | None,
    "height": int | None,
    "embedUrl": str | None,
    "startTime": int | None,
    "externalUrl": str | None,
    "externalSiteName": str | None,
    "previewData": list[int] | None,
    "paid": bool | None,
    "token": str | None,
    "collage": VideoCollage | None,
    "transcription": str | None,
    "transcriptionStatus": str | None,
    "wave": list[int] | None,
    "thumbhash": list[int] | None,
    },
    total=False,
)

ControlAttachment = TypedDict(
    "ControlAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "event": str,
    "userIds": list[int] | None,
    "title": str | None,
    "token": str | None,
    "photoToken": str | None,
    "crop": Crop | None,
    "userId": int | None,
    "url": str | None,
    "fullUrl": str | None,
    "message": str | None,
    "shortMessage": str | None,
    "showHistory": bool | None,
    "chatType": str | None,
    "pinnedMessage": Message | None,
    "startPayload": str | None,
    },
    total=False,
)

OutgoingGeoPositionAttachment = TypedDict(
    "OutgoingGeoPositionAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "latitude": float,
    "longitude": float,
    "zoom": float | None,
    },
    total=False,
)

OutgoingPhotoAttachment = TypedDict(
    "OutgoingPhotoAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "photoToken": str | None,
    },
    total=False,
)

OutgoingPollAttachment = TypedDict(
    "OutgoingPollAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "pollId": int | None,
    "title": str,
    "answers": list[PollAnswer],
    "settings": int,
    },
    total=False,
)

ReplyKeyboardAttachment = TypedDict(
    "ReplyKeyboardAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "keyboard": list[list[ReplyButton]],
    "defaultInputDisabled": bool | None,
    },
    total=False,
)

GeoPositionAttachment = TypedDict(
    "GeoPositionAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    "latitude": float,
    "longitude": float,
    "zoom": float | None,
    },
    total=False,
)

LogCallEventParams = TypedDict(
    "LogCallEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    "call_id": str | None,
    "is_group": bool | None,
    "event_label_str": str | None,
    "event_label_int": int | None,
    "custom_feedback": str | None,
    "error_type": str | None,
    "source": str | None,
    "is_wave": bool | None,
    },
    total=False,
)

LogRegistrationEventParams = TypedDict(
    "LogRegistrationEventParams",
    {
    "_type": str,
    "deleted": bool | None,
    "screen": int | None,
    "reason": int | None,
    "value": int | None,
    "phoneCountry": str | None,
    "source": int | None,
    },
    total=False,
)

BaseAttachment = TypedDict(
    "BaseAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    },
    total=False,
)

OutgoingBaseAttachment = TypedDict(
    "OutgoingBaseAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    },
    total=False,
)
