# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AdminParticipant = TypedDict(
    "AdminParticipant",
    {
    "id": int | None,
    "permissions": int | None,
    "inviterId": int | None,
    "alias": str | None,
    },
    total=False,
)
