# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AnimojiSet = TypedDict(
    "AnimojiSet",
    {
    "id": int,
    "name": str,
    "iconUrl": str,
    "iconLottieUrl": str | None,
    "updateTime": int,
    "animojiIds": list[int],
    },
    total=False,
)
