# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.assets_recent_emoji_item import AssetsRecentEmojiItem
from models.assets_recent_item import AssetsRecentItem

from typing import TypedDict, Any

AssetsSection = TypedDict(
    "AssetsSection",
    {
    "id": str,
    "updateTime": int | None,
    "title": str | None,
    "stickers": list[int] | None,
    "marker": int | None,
    "totalCount": int | None,
    "collapsed": bool | None,
    "stickerSets": list[int] | None,
    "recentsList": list[AssetsRecentItem] | None,
    "recentEmojiList": list[AssetsRecentEmojiItem] | None,
    "animojiSetIds": list[int] | None,
    "reactions": list[int] | None,
    },
    total=False,
)
