# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.photo_attachment import PhotoAttachment

from typing import TypedDict, Any

AssetsRecentItem = TypedDict(
    "AssetsRecentItem",
    {
    "type": str | None,
    "id": int | None,
    "stickerId": int | None,
    "gif": PhotoAttachment | None,
    },
    total=False,
)
