# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AssetsRecentEmojiItem = TypedDict(
    "AssetsRecentEmojiItem",
    {
    "id": int | None,
    "type": str | None,
    "value": str | None,
    },
    total=False,
)
