# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AttachmentsFileUploadFileUploadInfo = TypedDict(
    "AttachmentsFileUploadFileUploadInfo",
    {
    "fileId": int,
    "url": str,
    "token": str,
    },
    total=False,
)
