# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AttachmentsVideoUploadVideoUploadInfo = TypedDict(
    "AttachmentsVideoUploadVideoUploadInfo",
    {
    "url": str,
    "videoId": int,
    "token": str,
    },
    total=False,
)
