# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.auth_one_me_password_challenge_config import AuthOneMePasswordChallengeConfig

from typing import TypedDict, Any

AuthOneMePasswordChallenge = TypedDict(
    "AuthOneMePasswordChallenge",
    {
    "hint": str | None,
    "email": str | None,
    "trackId": str,
    "config": AuthOneMePasswordChallengeConfig | None,
    },
    total=False,
)
