# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AuthOneMeTokenAttributes = TypedDict(
    "AuthOneMeTokenAttributes",
    {
    "token": str,
    },
    total=False,
)
