# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AuthOneMePasswordChallengeConfig = TypedDict(
    "AuthOneMePasswordChallengeConfig",
    {
    "passMinLen": int | None,
    "passMaxLen": int | None,
    "hintMaxLen": int | None,
    },
    total=False,
)
