# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AuthOneMeDetails2FAResponsePassword = TypedDict(
    "AuthOneMeDetails2FAResponsePassword",
    {
    "enabled": bool,
    "hint": str | None,
    "email": str | None,
    },
    total=False,
)
