# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AuthOneMeAuthCheckResponseStatus = TypedDict(
    "AuthOneMeAuthCheckResponseStatus",
    {
    "loginAvailable": bool | None,
    "expiresAt": int | None,
    },
    total=False,
)
