# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

AvatarInfo = TypedDict(
    "AvatarInfo",
    {
    "id": int,
    "url": str,
    "def": bool | None,
    },
    total=False,
)
