# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

BannerProtoV1 = TypedDict(
    "BannerProtoV1",
    {
    "id": str,
    "title": str,
    "isTitleAnimated": bool | None,
    "description": str | None,
    "priority": int,
    "repeat": int | None,
    "rerun": int,
    "animojiId": int,
    "url": str,
    "type": int | None,
    },
    total=False,
)
