# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Banner = TypedDict(
    "Banner",
    {
    "id": str,
    "title": str,
    "settings": int | None,
    "description": str | None,
    "priority": int,
    "repeat": int | None,
    "rerun": int | None,
    "animojiId": int | None,
    "url": str | None,
    "type": int | None,
    },
    total=False,
)
