# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

BaseAttachment = TypedDict(
    "BaseAttachment",
    {
    "_type": str,
    "deleted": bool | None,
    },
    total=False,
)
