# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.bot_text import BotText

from typing import TypedDict, Any

BotStartMessage = TypedDict(
    "BotStartMessage",
    {
    "media": dict | None,
    "text": BotText,
    },
    total=False,
)
