# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

BotBotCommand = TypedDict(
    "BotBotCommand",
    {
    "botId": int,
    "name": str,
    "description": str | None,
    },
    total=False,
)
