# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Button = TypedDict(
    "Button",
    {
    "type": str | None,
    "text": str | None,
    "intent": str | None,
    "url": str | None,
    "payload": str | None,
    "quick": bool | None,
    "contactId": int | None,
    },
    total=False,
)
