# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

CallRateParams = TypedDict(
    "CallRateParams",
    {
    "limit": int | None,
    "sdk-limit": int | None,
    "duration": int | None,
    "delay": int | None,
    },
    total=False,
)
