# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.message import Message

from typing import TypedDict, Any

CallHistory = TypedDict(
    "CallHistory",
    {
    "chatId": int,
    "chatType": str,
    "contactIds": list[int] | None,
    "message": Message,
    },
    total=False,
)
