# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.folder_widget import FolderWidget
from models.map_filter_subjects import MapFilterSubjects
from models.message_element import MessageElement

from typing import TypedDict, Any

ChatFolder = TypedDict(
    "ChatFolder",
    {
    "id": str,
    "title": str,
    "emoji": str | None,
    "include": list[int] | None,
    "favorites": list[int] | None,
    "filters": list[int] | None,
    "options": list[int] | None,
    "updateTime": int,
    "elements": list[MessageElement] | None,
    "templateId": int | None,
    "filterSubjects": MapFilterSubjects | None,
    "widgets": list[FolderWidget] | None,
    "sourceId": int | None,
    },
    total=False,
)
