# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

ChatReactionsSettings = TypedDict(
    "ChatReactionsSettings",
    {
    "chatId": int | None,
    "isActive": bool | None,
    "updateTime": int,
    "count": int | None,
    "included": bool | None,
    "reactionIds": list[str] | None,
    },
    total=False,
)
