# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

ChatSettings = TypedDict(
    "ChatSettings",
    {
    "dontDisturbUntil": int | None,
    "sound": bool | None,
    "vibr": bool | None,
    "led": bool | None,
    "favIndex": int | None,
    "favMoveToConvId": int | None,
    "favMovePosition": int | None,
    },
    total=False,
)
