# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.admin_participant import AdminParticipant
from models.chat_reactions_settings import ChatReactionsSettings
from models.map_subject import MapSubject
from models.message import Message
from models.video_conversation import VideoConversation

from typing import TypedDict, Any

Chat = TypedDict(
    "Chat",
    {
    "id": int,
    "type": str,
    "status": str,
    "owner": int,
    "participants": dict[str, int],
    "participantsCount": int | None,
    "created": int,
    "joinTime": int | None,
    "title": str | None,
    "baseIconUrl": str | None,
    "baseRawIconUrl": str | None,
    "lastMessage": Message | None,
    "lastEventTime": int,
    "cid": int | None,
    "newMessages": int | None,
    "prevMessageId": int | None,
    "restrictions": int | None,
    "access": str | None,
    "link": str | None,
    "description": str | None,
    "admins": list[int] | None,
    "adminParticipants": dict[str, AdminParticipant] | None,
    "options": dict[str, bool] | None,
    "pinnedMessage": Message | None,
    "hidePinnedMessage": bool | None,
    "unreadReply": bool | None,
    "unreadPin": bool | None,
    "blockedParticipantsCount": int | None,
    "participantsMarker": int | None,
    "videoConversation": VideoConversation | None,
    "hasBots": bool | None,
    "isSuspended": bool | None,
    "modified": int | None,
    "liveLocationMessageIds": dict[str, int] | None,
    "lastMentionMessageId": int | None,
    "lastDelayedUpdateTime": int | None,
    "lastFireDelayedErrorTime": int | None,
    "lastReactedMessageId": int | None,
    "lastReaction": str | None,
    "markedAsUnread": bool | None,
    "invitedBy": int | None,
    "subject": MapSubject | None,
    "messagesCount": int | None,
    "reactions": ChatReactionsSettings | None,
    "joinRequestTime": int | None,
    "liveStreamUpdateTime": int | None,
    "pendingJoinRequestsCount": int | None,
    "participantSettings": int | None,
    "commentsBlacklistCount": int | None,
    },
    total=False,
)
