# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.contact import Contact
from models.presence import Presence

from typing import TypedDict, Any

ChatMember = TypedDict(
    "ChatMember",
    {
    "contact": Contact | None,
    "presence": Presence | None,
    "readMark": int | None,
    "blockedCommentsTime": int | None,
    },
    total=False,
)
