# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

CommentsInfo = TypedDict(
    "CommentsInfo",
    {
    "totalCount": int,
    },
    total=False,
)
