# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.complain_reasons_get_complains_type_reason_list import ComplainReasonsGetComplainsTypeReasonList

from typing import TypedDict, Any

ComplainReasonsGetComplainsReason = TypedDict(
    "ComplainReasonsGetComplainsReason",
    {
    "typeId": int,
    "reasons": list[ComplainReasonsGetComplainsTypeReasonList],
    },
    total=False,
)
