# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

ComplainReasonsGetComplainsTypeReasonList = TypedDict(
    "ComplainReasonsGetComplainsTypeReasonList",
    {
    "reasonId": int,
    "reasonTitle": str,
    },
    total=False,
)
