# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.chat_settings import ChatSettings
from models.server_settings import ServerSettings
from models.user_settings import UserSettings

from typing import TypedDict, Any

Configuration = TypedDict(
    "Configuration",
    {
    "hash": str,
    "chats": dict[str, ChatSettings] | None,
    "server": ServerSettings | None,
    "experiments": ServerSettings | None,
    "user": UserSettings | None,
    },
    total=False,
)
