# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

ContactName = TypedDict(
    "ContactName",
    {
    "firstName": str | None,
    "lastName": str | None,
    "type": str,
    },
    total=False,
)
