# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.contact_name import ContactName
from models.menu_button import MenuButton

from typing import TypedDict, Any

Contact = TypedDict(
    "Contact",
    {
    "id": int,
    "updateTime": int,
    "photoId": int | None,
    "baseUrl": str | None,
    "baseRawUrl": str | None,
    "names": list[ContactName] | None,
    "status": str | None,
    "accountStatus": int | None,
    "phone": int | None,
    "gender": int | None,
    "bday": str | None,
    "options": list[str] | None,
    "link": str | None,
    "description": str | None,
    "webApp": str | None,
    "menuButton": MenuButton | None,
    "profileStatus": str | None,
    "country": str | None,
    "organizationIds": list[int] | None,
    "registrationTime": int | None,
    },
    total=False,
)
