# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Creation2FAConfig = TypedDict(
    "Creation2FAConfig",
    {
    "enabled": bool | None,
    "pass_min_len": int | None,
    "pass_max_len": int | None,
    "hint_max_len": int | None,
    },
    total=False,
)
