# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Crop = TypedDict(
    "Crop",
    {
    "x1": float,
    "y1": float,
    "x2": float,
    "y2": float,
    },
    total=False,
)
