# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

DelayedTamAttributes = TypedDict(
    "DelayedTamAttributes",
    {
    "timeToFire": int,
    "notifySender": bool | None,
    },
    total=False,
)
