# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

FolderWidget = TypedDict(
    "FolderWidget",
    {
    "id": int,
    "name": str,
    "description": str | None,
    "iconUrl": str | None,
    "appId": int | None,
    "startParam": str | None,
    "url": str | None,
    },
    total=False,
)
