# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Icon = TypedDict(
    "Icon",
    {
    "url": str,
    "width": int,
    "height": int,
    },
    total=False,
)
