# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.button import Button

from typing import TypedDict, Any

Keyboard = TypedDict(
    "Keyboard",
    {
    "buttons": list[list[Button]],
    },
    total=False,
)
