# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

LiveStream = TypedDict(
    "LiveStream",
    {
    "chatId": int,
    "updateTime": int,
    "media": dict | None,
    },
    total=False,
)
