# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.log_search_event_params_item import LogSearchEventParamsItem

from typing import TypedDict, Any

LogSearchEventParamsItems = TypedDict(
    "LogSearchEventParamsItems",
    {
    "items": list[LogSearchEventParamsItem],
    },
    total=False,
)
