# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.log_search_event_params_item_meta import LogSearchEventParamsItemMeta

from typing import TypedDict, Any

LogSearchEventParamsItem = TypedDict(
    "LogSearchEventParamsItem",
    {
    "itemMeta": LogSearchEventParamsItemMeta,
    },
    total=False,
)
