# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.log_search_event_params_items import LogSearchEventParamsItems

from typing import TypedDict, Any

LogSearchEventParamsSections = TypedDict(
    "LogSearchEventParamsSections",
    {
    "LOCAL_SEARCH": LogSearchEventParamsItems | None,
    },
    total=False,
)
