# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

LogSearchEventParamsCounters = TypedDict(
    "LogSearchEventParamsCounters",
    {
    "LOCAL_SEARCH": int | None,
    },
    total=False,
)
