# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.log_search_event_params_chat_meta import LogSearchEventParamsChatMeta

from typing import TypedDict, Any

LogSearchEventParamsItemMeta = TypedDict(
    "LogSearchEventParamsItemMeta",
    {
    "chatMeta": LogSearchEventParamsChatMeta,
    },
    total=False,
)
