# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

LogLogEvent = TypedDict(
    "LogLogEvent",
    {
    "time": int | None,
    "type": str,
    "event": str,
    "sessionId": int,
    "userId": int | None,
    "user2Id": int | None,
    "params": dict | None,
    },
    total=False,
)
