# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

LogSearchEventParamsChatMeta = TypedDict(
    "LogSearchEventParamsChatMeta",
    {
    "conversationType": int,
    "conversationId": int,
    },
    total=False,
)
