# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MapSubject = TypedDict(
    "MapSubject",
    {
    "organizationIds": list[int] | None,
    },
    total=False,
)
