# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageReactionEntry = TypedDict(
    "MessageReactionEntry",
    {
    "userId": int | None,
    "reaction": str | None,
    },
    total=False,
)
