# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageReactionCounter = TypedDict(
    "MessageReactionCounter",
    {
    "reaction": str,
    "count": int,
    },
    total=False,
)
