# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.message_element_attributes_map import MessageElementAttributesMap

from typing import TypedDict, Any

MessageElement = TypedDict(
    "MessageElement",
    {
    "entityId": int | None,
    "entityName": str | None,
    "type": str,
    "from": int | None,
    "length": int | None,
    "attributes": MessageElementAttributesMap | None,
    },
    total=False,
)
