# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageLink = TypedDict(
    "MessageLink",
    {
    "type": str,
    "chatId": int | None,
    "postId": int | None,
    "chatName": str | None,
    "chatLink": str | None,
    "message": dict,
    },
    total=False,
)
