# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessagePreview = TypedDict(
    "MessagePreview",
    {
    "text": str | None,
    "attachment": dict | None,
    },
    total=False,
)
