# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageStats = TypedDict(
    "MessageStats",
    {
    "views": int | None,
    "forwards": int | None,
    },
    total=False,
)
