# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.message_reaction_counter import MessageReactionCounter

from typing import TypedDict, Any

MessageReactionInfo = TypedDict(
    "MessageReactionInfo",
    {
    "counters": list[MessageReactionCounter] | None,
    "totalCount": int | None,
    "yourReaction": str | None,
    },
    total=False,
)
