# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageReaction = TypedDict(
    "MessageReaction",
    {
    "reactionType": str,
    "id": str,
    },
    total=False,
)
