# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

MessageElementAttributesMap = TypedDict(
    "MessageElementAttributesMap",
    {
    "url": str | None,
    "animojiSetId": int | None,
    "animojiLottieUrl": str | None,
    },
    total=False,
)
