# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.comments_info import CommentsInfo
from models.delayed_tam_attributes import DelayedTamAttributes
from models.message_element import MessageElement
from models.message_preview import MessagePreview
from models.message_reaction_info import MessageReactionInfo
from models.message_stats import MessageStats

from typing import TypedDict, Any

Message = TypedDict(
    "Message",
    {
    "id": int,
    "time": int,
    "type": str,
    "updateTime": int | None,
    "status": str | None,
    "sender": int | None,
    "cid": int | None,
    "text": str | None,
    "zoom": int | None,
    "attaches": list[dict] | None,
    "link": dict | None | None,
    "ttl": int | None,
    "viewTime": int | None,
    "options": int | None,
    "liveUntil": int | None,
    "messagePreview": MessagePreview | None,
    "elements": list[MessageElement] | None,
    "reactionInfo": MessageReactionInfo | None,
    "stats": MessageStats | None,
    "delayedAttributes": DelayedTamAttributes | None,
    "commentsInfo": CommentsInfo | None,
    },
    total=False,
)
