# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

OpusSupport = TypedDict(
    "OpusSupport",
    {
    "windows": bool | None,
    "macos": bool | None,
    "linux": bool | None,
    },
    total=False,
)
