# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Organization = TypedDict(
    "Organization",
    {
    "id": int,
    "name": str,
    "description": str | None,
    "parentId": int | None,
    "folderTemplateId": int | None,
    "baseIconUrl": str | None,
    "emojiStatusId": int | None,
    "updateTime": int,
    },
    total=False,
)
