# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.delayed_tam_attributes import DelayedTamAttributes
from models.message_element import MessageElement
from models.outgoing_message_outgoing_message_link import OutgoingMessageOutgoingMessageLink

from typing import TypedDict, Any

OutgoingMessage = TypedDict(
    "OutgoingMessage",
    {
    "cid": int | None,
    "text": str | None,
    "zoom": int | None,
    "attaches": list[dict] | None,
    "link": OutgoingMessageOutgoingMessageLink | None,
    "attachMEL": bool | None,
    "ttl": int | None,
    "isLive": bool | None,
    "elements": list[MessageElement] | None,
    "delayedAttributes": DelayedTamAttributes | None,
    },
    total=False,
)
