# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

OutgoingMessageOutgoingMessageLink = TypedDict(
    "OutgoingMessageOutgoingMessageLink",
    {
    "type": str,
    "chatId": int | None,
    "postId": int | None,
    "messageId": int,
    },
    total=False,
)
