# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

PhotoAttachment = TypedDict(
    "PhotoAttachment",
    {
    "photoId": int | None,
    "url": str | None,
    "baseUrl": str | None,
    "width": int | None,
    "height": int | None,
    "gif": bool | None,
    "previewData": list[int] | None,
    "mp4Url": str | None,
    "photoToken": str | None,
    "sensitive": bool | None,
    },
    total=False,
)
