# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

PollsGetPollUpdatesParametersChatPollUpdate = TypedDict(
    "PollsGetPollUpdatesParametersChatPollUpdate",
    {
    "messageId": int,
    "pollId": int,
    },
    total=False,
)
