# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.poll_state_results import PollStateResults

from typing import TypedDict, Any

PollState = TypedDict(
    "PollState",
    {
    "total": int,
    "result": list[PollStateResults] | None,
    "voterPreviewIds": list[int] | None,
    },
    total=False,
)
