# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

PollTtl = TypedDict(
    "PollTtl",
    {
    "chat": int | None,
    "bigchat": int | None,
    "channel": int | None,
    },
    total=False,
)
