# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

PollAnswer = TypedDict(
    "PollAnswer",
    {
    "text": str,
    "answerId": int | None,
    },
    total=False,
)
