# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.poll_answer import PollAnswer
from models.poll_state import PollState
from models.poll_state_results import PollStateResults

from typing import TypedDict, Any

Poll = TypedDict(
    "Poll",
    {
    "pollId": int,
    "title": str,
    "answers": list[PollAnswer],
    "settings": int,
    "state": PollState,
    "total": int,
    "result": list[PollStateResults] | None,
    "voterPreviewIds": list[int] | None,
    "version": int | None,
    },
    total=False,
)
