# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

PollAnswerStats = TypedDict(
    "PollAnswerStats",
    {
    "userId": int,
    "timestamp": int,
    },
    total=False,
)
