# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Presence = TypedDict(
    "Presence",
    {
    "on": str | None,
    "status": int | None,
    "seen": int | None,
    },
    total=False,
)
