# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.avatar_info import AvatarInfo

from typing import TypedDict, Any

PresetAvatarsInfo = TypedDict(
    "PresetAvatarsInfo",
    {
    "name": str,
    "avatars": list[AvatarInfo],
    },
    total=False,
)
