# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.contact import Contact

from typing import TypedDict, Any

Profile = TypedDict(
    "Profile",
    {
    "contact": Contact,
    "profileOptions": list[int] | None,
    },
    total=False,
)
