# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

RejectedParticipant = TypedDict(
    "RejectedParticipant",
    {
    "id": int,
    "errorCode": str,
    },
    total=False,
)
