# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.outgoing_message import OutgoingMessage

from typing import TypedDict, Any

ReplyButton = TypedDict(
    "ReplyButton",
    {
    "type": str,
    "message": OutgoingMessage,
    "intent": str | None,
    "text": str | None,
    "image": dict | None,
    },
    total=False,
)
