# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

Session = TypedDict(
    "Session",
    {
    "time": int,
    "client": str,
    "info": str,
    "location": str,
    "current": bool | None,
    },
    total=False,
)
