# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

ShowWebappSearchCaseItem = TypedDict(
    "ShowWebappSearchCaseItem",
    {
    "id": int | None,
    "icon": str | None,
    "title": str | None,
    },
    total=False,
)
