# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.show_webapp_search_case_item import ShowWebappSearchCaseItem

from typing import TypedDict, Any

ShowWebappSearchCase = TypedDict(
    "ShowWebappSearchCase",
    {
    "items": list[ShowWebappSearchCaseItem] | None,
    },
    total=False,
)
