# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

StickerSet = TypedDict(
    "StickerSet",
    {
    "id": int,
    "name": str,
    "iconUrl": str,
    "iconLottieUrl": str | None,
    "authorId": int | None,
    "updateTime": int,
    "stickers": list[int],
    "link": str,
    "installCount": int | None,
    },
    total=False,
)
