# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.message_element import MessageElement

from typing import TypedDict, Any

TextObject = TypedDict(
    "TextObject",
    {
    "text": str,
    "elements": list[MessageElement] | None,
    },
    total=False,
)
