# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

UserAgent = TypedDict(
    "UserAgent",
    {
    "deviceType": str,
    "appVersion": str,
    "osVersion": str,
    "locale": str,
    "deviceLocale": str,
    "deviceName": str,
    "screen": str,
    "timezone": str,
    "buildNumber": int,
    },
    total=False,
)
