# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

UserSettings = TypedDict(
    "UserSettings",
    {
    "SHOW_READ_MARK": bool | None,
    "PUSH_NEW_CONTACTS": bool | None,
    "FIND_BY_PHONE": bool | None,
    "PUSH_DETAILS": bool | None,
    "DONT_DISTURB_UNTIL": int | None,
    "CHATS_PUSH_NOTIFICATION": str | None,
    "DIALOGS_PUSH_NOTIFICATION": str | None,
    "CHATS_PUSH_SOUND": str | None,
    "PUSH_SOUND": str | None,
    "HIDDEN": bool | None,
    "CHATS_INVITE": str | None,
    "INCOMING_CALL": str | None,
    "INACTIVE_TTL": str | None,
    "M_CALL_PUSH_NOTIFICATION": str | None,
    "STICKERS_SUGGEST": str | None,
    "AUDIO_TRANSCRIPTION_ENABLED": bool | None,
    "ALT_KEYBOARD": bool | None,
    "SAFE_MODE": bool | None,
    "SEARCH_BY_PHONE": str | None,
    "UNSAFE_FILES": bool | None,
    "CONTENT_LEVEL_ACCESS": bool | None,
    "FAMILY_PROTECTION": str | None,
    "PHONE_NUMBER_PRIVACY": str | None,
    },
    total=False,
)
