# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

VideoCollage = TypedDict(
    "VideoCollage",
    {
    "url": str | None,
    "frequency": int | None,
    "height": int | None,
    "width": int | None,
    "count": int | None,
    },
    total=False,
)
