# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

VideoConversation = TypedDict(
    "VideoConversation",
    {
    "conversationId": str,
    "joinLink": str | None,
    "startedAt": int | None,
    "approxParticipantsCount": int | None,
    "previewParticipantIds": list[int] | None,
    "type": int | None,
    },
    total=False,
)
