# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.contact import Contact

from typing import TypedDict, Any

VideoConference = TypedDict(
    "VideoConference",
    {
    "owner": Contact,
    "joinLink": str,
    "conferenceId": str,
    "callType": str,
    "callName": str | None,
    "participantsCount": int | None,
    "startAt": int | None,
    "previewParticipantIds": list[int] | None,
    "chatId": int | None,
    "type": int | None,
    },
    total=False,
)
