# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

VideoMessageConfig = TypedDict(
    "VideoMessageConfig",
    {
    "duration": int | None,
    "quality": int | None,
    "detect-upload": int | None,
    "long-press-mode": int | None,
    },
    total=False,
)
