# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

WebAppEntry = TypedDict(
    "WebAppEntry",
    {
    "icon": str | None,
    "title": str | None,
    "appId": int | None,
    "startParam": str | None,
    },
    total=False,
)
