# Autogenerated. DO NOT EDIT

from __future__ import annotations

from models.icon import Icon
from models.text_object import TextObject

from typing import TypedDict, Any

WidgetContent = TypedDict(
    "WidgetContent",
    {
    "type": int,
    "media": dict | None,
    "text": TextObject | None,
    "icon": Icon | None,
    },
    total=False,
)
