# Autogenerated. DO NOT EDIT

from __future__ import annotations

from typing import TypedDict, Any

YMapConfig = TypedDict(
    "YMapConfig",
    {
    "tile": str | None,
    "geocoder": str | None,
    "static": str | None,
    },
    total=False,
)
