[package]
name = "dumper_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
iced-x86 = "1.21"
goblin = "0.9"
msvc-demangler = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
memchr = "2.7"

