// Autogenerated. DO NOT EDIT

package main

import (
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"sync"
	"time"

	"github.com/vmihailenco/msgpack/v5"
)

// Client is the main API client.
type Client struct {
	AppVersion  string
	BuildNumber int32
	VerboseLog  bool
	conn        net.Conn
	seq         uint8
	mu          sync.Mutex
	writeMu     sync.Mutex
	pending     map[uint8]chan *Packet
	handlers    map[uint16][]func(*Packet)
	closeCh     chan struct{}
}

func NewClient() *Client {
	return &Client{
		AppVersion:  "26.15.2",
		BuildNumber: 69628,
		VerboseLog:  true,
		pending:     make(map[uint8]chan *Packet),
		handlers:    make(map[uint16][]func(*Packet)),
		closeCh:     make(chan struct{}),
	}
}

// DefaultServerAddr is the default TCP server address.
const DefaultServerAddr = "api.oneme.ru:443"

func (c *Client) ConnectTCP(addr string) error {
	conn, err := tls.Dial("tcp", addr, &tls.Config{
		ServerName: "",
	})
	if err != nil {
		return err
	}
	c.conn = conn
	go c.readLoop()
	return nil
}

func (c *Client) Connect() error {
	return c.ConnectTCP(DefaultServerAddr)
}

func (c *Client) Close() error {
	close(c.closeCh)
	if c.conn != nil {
		return c.conn.Close()
	}
	return nil
}

func (c *Client) cancelPending(err error) {
	c.mu.Lock()
	defer c.mu.Unlock()
	errPkt := &Packet{Cmd: 3, Payload: err.Error()}
	for seq, ch := range c.pending {
		ch <- errPkt
		delete(c.pending, seq)
	}
}

func (c *Client) readLoop() {
	var loopErr error
	defer func() {
		if loopErr != nil {
			c.cancelPending(loopErr)
		}
	}()

	for {
		select {
		case <-c.closeCh:
			return
		default:
		}
		header := make([]byte, 10)
		_, err := io.ReadFull(c.conn, header)
		if err != nil {
			loopErr = err
			log.Printf("tcp read header: %v", err)
			return
		}
		packedLen := int(header[6])<<24 | int(header[7])<<16 | int(header[8])<<8 | int(header[9])
		payloadLen := packedLen & 0xFFFFFF
		body := make([]byte, payloadLen)
		_, err = io.ReadFull(c.conn, body)
		if err != nil {
			loopErr = err
			log.Printf("tcp read body: %v", err)
			return
		}
		p, err := UnpackPacket(append(header, body...))
		if err != nil {
			log.Printf("unpack error: %v", err)
			continue
		}
		if c.VerboseLog {
			data, _ := json.Marshal(p)
			log.Printf("<<< %s", string(data))
		}
		c.dispatch(p)
	}
}

var notificationOpcodes = map[uint16]struct{}{
	120: struct{}{},
	121: struct{}{},
	128: struct{}{},
	129: struct{}{},
	130: struct{}{},
	131: struct{}{},
	132: struct{}{},
	134: struct{}{},
	135: struct{}{},
	136: struct{}{},
	137: struct{}{},
	140: struct{}{},
	142: struct{}{},
	150: struct{}{},
	154: struct{}{},
	155: struct{}{},
	156: struct{}{},
	159: struct{}{},
	277: struct{}{},
	292: struct{}{},
	293: struct{}{},
}

func (c *Client) dispatch(p *Packet) {
	c.mu.Lock()
	_, isNotification := notificationOpcodes[p.Opcode]
	ch, ok := c.pending[p.Seq]
	if ok && !isNotification {
		delete(c.pending, p.Seq)
		c.mu.Unlock()
		ch <- p
		return
	}
	c.mu.Unlock()
	c.mu.Lock()
	handlers := c.handlers[p.Opcode]
	c.mu.Unlock()
	for _, h := range handlers {
		h(p)
	}
}

func (c *Client) On(opcode uint16, handler func(*Packet)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.handlers[opcode] = append(c.handlers[opcode], handler)
}

func (c *Client) sendRaw(opcode uint16, payload interface{}) (*Packet, error) {
	c.mu.Lock()
	seq := c.seq
	c.seq++
	if _, busy := c.pending[seq]; busy {
		c.mu.Unlock()
		return nil, errors.New("seq overflow: too many concurrent requests")
	}
	ch := make(chan *Packet, 1)
	c.pending[seq] = ch
	c.mu.Unlock()

	data, encErr := PackPacket(ProtocolVersion, 0, seq, opcode, payload)
	if encErr != nil {
		c.mu.Lock()
		delete(c.pending, seq)
		c.mu.Unlock()
		return nil, encErr
	}

	if c.VerboseLog {
		raw, _ := json.Marshal(payload)
		log.Printf(">>> OP=%d %s", opcode, string(raw))
	}
	c.writeMu.Lock()
	_, writeErr := c.conn.Write(data)
	c.writeMu.Unlock()
	if writeErr != nil {
		c.mu.Lock()
		delete(c.pending, seq)
		c.mu.Unlock()
		return nil, writeErr
	}

	select {
	case resp := <-ch:
		if m, ok := resp.Payload.(map[string]interface{}); ok {
			apiErr := ApiError{}
			if v, ok := m["error"].(string); ok {
				apiErr.Error = v
			}
			if v, ok := m["localizedMessage"].(string); ok {
				apiErr.LocalizedMessage = v
			}
			if v, ok := m["message"].(string); ok {
				apiErr.Message = v
			}
			if v, ok := m["title"].(string); ok {
				apiErr.Title = v
			}
			if apiErr.Error != "" && apiErr.LocalizedMessage != "" && apiErr.Message != "" && apiErr.Title != "" {
				return nil, fmt.Errorf("api error: %s", apiErr.ErrorString())
			}
		}
		if resp.Opcode != opcode {
			return nil, fmt.Errorf("opcode mismatch: expected %d, got %d", opcode, resp.Opcode)
		}
		return resp, nil
	case <-time.After(30 * time.Second):
		c.mu.Lock()
		delete(c.pending, seq)
		c.mu.Unlock()
		return nil, fmt.Errorf("request timeout (opcode=%d seq=%d)", opcode, seq)
	}
}

func (c *Client) Send(opcode uint16, payload interface{}, respPayload interface{}) error {
	pkt, err := c.sendRaw(opcode, payload)
	if err != nil {
		return err
	}
	if respPayload != nil {
		raw, err := msgpack.Marshal(pkt.Payload)
		if err != nil {
			return fmt.Errorf("encode response: %w", err)
		}
		if err := msgpack.Unmarshal(raw, respPayload); err != nil {
			return fmt.Errorf("decode response: %w", err)
		}
	}
	return nil
}

// SendPingPayload sends Api::OneMe::Packets::Ping::Payload (fire-and-forget).
func (c *Client) SendPingPayload(req *PingPayload) error {
	_, err := c.sendRaw(1, req)
	return err
}

// SendOpcode5 sends Api::OneMe::Packets::Log::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode5(req *LogParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(5, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode5 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSessionInit sends Api::OneMe::Packets::SessionInit::Payload and returns Api::OneMe::Packets::SessionInit::Response.
func (c *Client) SendSessionInit(req *SessionInitPayload) (*SessionInitResponse, error) {
	pkt, err := c.sendRaw(OpcodeSessionInit, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SessionInitResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SessionInitResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSessionInit raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendProfile sends Api::OneMe::Packets::Profile::Parameters and returns Api::OneMe::Packets::Profile::Response.
func (c *Client) SendProfile(req *ProfileParameters) (*ProfileResponse, error) {
	pkt, err := c.sendRaw(OpcodeProfile, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ProfileResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ProfileResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendProfile raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeAuthRequest sends Api::OneMe::Packets::Auth::OneMe::AuthRequest::Parameters and returns Api::OneMe::Packets::Auth::OneMe::AuthRequest::Response.
func (c *Client) SendAuthOneMeAuthRequest(req *AuthOneMeAuthRequestParameters) (*AuthOneMeAuthRequestResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeAuthRequest, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeAuthRequestResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeAuthRequestResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeAuthRequest raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeAuth sends Api::OneMe::Packets::Auth::OneMe::Auth::Parameters and returns Api::OneMe::Packets::Auth::OneMe::Auth::Response.
func (c *Client) SendAuthOneMeAuth(req *AuthOneMeAuthParameters) (*AuthOneMeAuthResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeAuth, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeAuthResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeAuthResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeAuth raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthLogin sends Api::OneMe::Packets::Auth::Login::Parameters and returns Api::OneMe::Packets::Auth::Login::Response.
func (c *Client) SendAuthLogin(req *AuthLoginParameters) (*AuthLoginResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthLogin, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthLoginResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthLoginResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthLogin raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode20 sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode20(req *EmptyParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(20, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode20 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendConfig sends Api::OneMe::Packets::Config::Parameters and returns Api::OneMe::Packets::Config::Response.
func (c *Client) SendConfig(req *ConfigParameters) (*ConfigResponse, error) {
	pkt, err := c.sendRaw(OpcodeConfig, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ConfigResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ConfigResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendConfig raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeAuthConfirm sends Api::OneMe::Packets::Auth::OneMe::AuthConfirm::Parameters and returns Api::OneMe::Packets::Auth::OneMe::AuthConfirm::Response.
func (c *Client) SendAuthOneMeAuthConfirm(req *AuthOneMeAuthConfirmParameters) (*AuthOneMeAuthConfirmResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeAuthConfirm, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeAuthConfirmResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeAuthConfirmResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeAuthConfirm raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAvatarPresetAvatar sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::Avatar::PresetAvatar::Response.
func (c *Client) SendAvatarPresetAvatar(req *EmptyParameters) (*AvatarPresetAvatarResponse, error) {
	pkt, err := c.sendRaw(OpcodeAvatarPresetAvatar, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AvatarPresetAvatarResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AvatarPresetAvatarResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAvatarPresetAvatar raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsGetAssetStickerSet sends Api::OneMe::Packets::Assets::GetAsset::Common::Parameters and returns Api::OneMe::Packets::Assets::GetAsset::StickerSet::Response.
func (c *Client) SendAssetsGetAssetStickerSet(req *AssetsGetAssetCommonParameters) (*AssetsGetAssetStickerSetResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsGetAssetStickerSet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsGetAssetStickerSetResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsGetAssetStickerSetResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsGetAssetStickerSet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsUpdate sends Api::OneMe::Packets::Assets::Update::Parameters and returns Api::OneMe::Packets::Assets::Update::Response.
func (c *Client) SendAssetsUpdate(req *AssetsUpdateParameters) (*AssetsUpdateResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsUpdate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsUpdateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsUpdateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsUpdate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsGetByIdsAnimojiSet sends Api::OneMe::Packets::Assets::GetByIds::Common::Parameters and returns Api::OneMe::Packets::Assets::GetByIds::AnimojiSet::Response.
func (c *Client) SendAssetsGetByIdsAnimojiSet(req *AssetsGetByIdsCommonParameters) (*AssetsGetByIdsAnimojiSetResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsGetByIdsAnimojiSet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsGetByIdsAnimojiSetResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsGetByIdsAnimojiSetResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsGetByIdsAnimojiSet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsAdd sends Api::OneMe::Packets::Assets::Add::Parameters and returns Api::OneMe::Packets::Assets::Add::Response.
func (c *Client) SendAssetsAdd(req *AssetsAddParameters) (*AssetsAddResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsAdd, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsAddResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsAddResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsAdd raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactInfo sends Api::OneMe::Packets::Contact::ContactInfo::Parameters and returns Api::OneMe::Packets::Contact::ContactInfo::Response.
func (c *Client) SendContactContactInfo(req *ContactContactInfoParameters) (*ContactContactInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactUpdate sends Api::OneMe::Packets::Contact::ContactUpdate::Parameters and returns Api::OneMe::Packets::Contact::ContactUpdate::Response.
func (c *Client) SendContactContactUpdate(req *ContactContactUpdateParameters) (*ContactContactUpdateResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactUpdate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactUpdateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactUpdateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactUpdate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactPresence sends Api::OneMe::Packets::Contact::Presence::Parameters and returns Api::OneMe::Packets::Contact::Presence::Response.
func (c *Client) SendContactPresence(req *ContactPresenceParameters) (*ContactPresenceResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactPresence, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactPresenceResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactPresenceResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactPresence raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactList sends Api::OneMe::Packets::Contact::ContactList::Parameters and returns Api::OneMe::Packets::Contact::ContactList::Response.
func (c *Client) SendContactContactList(req *ContactContactListParameters) (*ContactContactListResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactList, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactListResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactListResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactList raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSearchContact sends Api::OneMe::Packets::Search::Contact::Parameters and returns Api::OneMe::Packets::Search::Contact::Response.
func (c *Client) SendSearchContact(req *SearchContactParameters) (*SearchContactResponse, error) {
	pkt, err := c.sendRaw(OpcodeSearchContact, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SearchContactResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SearchContactResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSearchContact raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactPhotos sends Api::OneMe::Packets::Contact::ContactPhotos::Parameters and returns Api::OneMe::Packets::Contact::ContactPhotos::Response.
func (c *Client) SendContactContactPhotos(req *ContactContactPhotosParameters) (*ContactContactPhotosResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactPhotos, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactPhotosResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactPhotosResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactPhotos raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactCreate sends Api::OneMe::Packets::Contact::ContactCreate::Parameters and returns Api::OneMe::Packets::Contact::ContactCreate::Response.
func (c *Client) SendContactContactCreate(req *ContactContactCreateParameters) (*ContactContactCreateResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactCreate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactCreateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactCreateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactCreate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactRemoveContactPhoto sends Api::OneMe::Packets::Contact::RemoveContactPhoto::Parameters and returns Api::OneMe::Packets::Contact::RemoveContactPhoto::Response.
func (c *Client) SendContactRemoveContactPhoto(req *ContactRemoveContactPhotoParameters) (*ContactRemoveContactPhotoResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactRemoveContactPhoto, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactRemoveContactPhotoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactRemoveContactPhotoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactRemoveContactPhoto raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendContactContactByPhone sends Api::OneMe::Packets::Contact::ContactByPhone::Parameters and returns Api::OneMe::Packets::Contact::ContactByPhone::Response.
func (c *Client) SendContactContactByPhone(req *ContactContactByPhoneParameters) (*ContactContactByPhoneResponse, error) {
	pkt, err := c.sendRaw(OpcodeContactContactByPhone, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ContactContactByPhoneResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ContactContactByPhoneResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendContactContactByPhone raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatInfo sends Api::OneMe::Packets::Chat::ChatInfo::Parameters and returns Api::OneMe::Packets::Chat::ChatInfo::Response.
func (c *Client) SendChatChatInfo(req *ChatChatInfoParameters) (*ChatChatInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatHistory sends Api::OneMe::Packets::Chat::ChatHistory::Parameters and returns Api::OneMe::Packets::Chat::ChatHistory::Response.
func (c *Client) SendChatChatHistory(req *ChatChatHistoryParameters) (*ChatChatHistoryResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatHistory, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatHistoryResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatHistoryResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatHistory raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatMark sends Api::OneMe::Packets::Chat::ChatMark::Parameters and returns Api::OneMe::Packets::Chat::ChatMark::Response.
func (c *Client) SendChatChatMark(req *ChatChatMarkParameters) (*ChatChatMarkResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatMark, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatMarkResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatMarkResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatMark raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatMedia sends Api::OneMe::Packets::Chat::ChatMedia::Parameters and returns Api::OneMe::Packets::Chat::ChatMedia::Response.
func (c *Client) SendChatChatMedia(req *ChatChatMediaParameters) (*ChatChatMediaResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatMedia, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatMediaResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatMediaResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatMedia raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode52 sends Api::OneMe::Packets::Chat::ChatDelete::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode52(req *ChatChatDeleteParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(52, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode52 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatList sends Api::OneMe::Packets::Chat::ChatList::Parameters and returns Api::OneMe::Packets::Chat::ChatList::Response.
func (c *Client) SendChatChatList(req *ChatChatListParameters) (*ChatChatListResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatList, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatListResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatListResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatList raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode54 sends Api::OneMe::Packets::Chat::ChatClear::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode54(req *ChatChatClearParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(54, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode54 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatUpdate sends Api::OneMe::Packets::Chat::ChatUpdate::Parameters and returns Api::OneMe::Packets::Chat::ChatUpdate::Response.
func (c *Client) SendChatChatUpdate(req *ChatChatUpdateParameters) (*ChatChatUpdateResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatUpdate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatUpdateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatUpdateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatUpdate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatCheckLink sends Api::OneMe::Packets::Chat::CheckLink::Parameters and returns Api::OneMe::Packets::Chat::CheckLink::Response.
func (c *Client) SendChatCheckLink(req *ChatCheckLinkParameters) (*ChatCheckLinkResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatCheckLink, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatCheckLinkResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatCheckLinkResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatCheckLink raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatJoin sends Api::OneMe::Packets::Chat::Join::Parameters and returns Api::OneMe::Packets::Chat::Join::Response.
func (c *Client) SendChatJoin(req *ChatJoinParameters) (*ChatJoinResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatJoin, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatJoinResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatJoinResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatJoin raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatLeave sends Api::OneMe::Packets::Chat::ChatLeave::Parameters and returns Api::OneMe::Packets::Chat::ChatLeave::Response.
func (c *Client) SendChatChatLeave(req *ChatChatLeaveParameters) (*ChatChatLeaveResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatLeave, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatLeaveResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatLeaveResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatLeave raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatMembers sends Api::OneMe::Packets::Chat::ChatMembers::Parameters and returns Api::OneMe::Packets::Chat::ChatMembers::Response.
func (c *Client) SendChatChatMembers(req *ChatChatMembersParameters) (*ChatChatMembersResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatMembers, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatMembersResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatMembersResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatMembers raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSearchPublic sends Api::OneMe::Packets::Search::Public::Parameters and returns Api::OneMe::Packets::Search::Public::Response.
func (c *Client) SendSearchPublic(req *SearchPublicParameters) (*SearchPublicResponse, error) {
	pkt, err := c.sendRaw(OpcodeSearchPublic, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SearchPublicResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SearchPublicResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSearchPublic raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatPersonalConfig sends Api::OneMe::Packets::Chat::PersonalConfig::Parameters and returns Api::OneMe::Packets::Chat::PersonalConfig::Response.
func (c *Client) SendChatPersonalConfig(req *ChatPersonalConfigParameters) (*ChatPersonalConfigResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatPersonalConfig, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatPersonalConfigResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatPersonalConfigResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatPersonalConfig raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendLiveStreamLiveStreamInfo sends Api::OneMe::Packets::LiveStream::LiveStreamInfo::Parameters and returns Api::OneMe::Packets::LiveStream::LiveStreamInfo::Response.
func (c *Client) SendLiveStreamLiveStreamInfo(req *LiveStreamLiveStreamInfoParameters) (*LiveStreamLiveStreamInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeLiveStreamLiveStreamInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*LiveStreamLiveStreamInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp LiveStreamLiveStreamInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendLiveStreamLiveStreamInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendMessagingSend sends Api::OneMe::Packets::Messaging::Send::Parameters and returns Api::OneMe::Packets::Messaging::Send::Response.
func (c *Client) SendMessagingSend(req *MessagingSendParameters) (*MessagingSendResponse, error) {
	pkt, err := c.sendRaw(OpcodeMessagingSend, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*MessagingSendResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp MessagingSendResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendMessagingSend raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode65 sends Api::OneMe::Packets::Typing::Send::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode65(req *TypingSendParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(65, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode65 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendMessagingDelete sends Api::OneMe::Packets::Messaging::Delete::Parameters and returns Api::OneMe::Packets::Messaging::Delete::Response.
func (c *Client) SendMessagingDelete(req *MessagingDeleteParameters) (*MessagingDeleteResponse, error) {
	pkt, err := c.sendRaw(OpcodeMessagingDelete, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*MessagingDeleteResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp MessagingDeleteResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendMessagingDelete raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendMessagingEdit sends Api::OneMe::Packets::Messaging::Edit::Parameters and returns Api::OneMe::Packets::Messaging::Edit::Response.
func (c *Client) SendMessagingEdit(req *MessagingEditParameters) (*MessagingEditResponse, error) {
	pkt, err := c.sendRaw(OpcodeMessagingEdit, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*MessagingEditResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp MessagingEditResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendMessagingEdit raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSearchChat sends Api::OneMe::Packets::Search::Chat::Parameters and returns Api::OneMe::Packets::Search::Chat::Response.
func (c *Client) SendSearchChat(req *SearchChatParameters) (*SearchChatResponse, error) {
	pkt, err := c.sendRaw(OpcodeSearchChat, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SearchChatResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SearchChatResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSearchChat raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode69 sends Api::OneMe::Packets::Calls::VideoChatEdit::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode69(req *CallsVideoChatEditParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(69, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode69 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendMessagingMsgGet sends Api::OneMe::Packets::Messaging::MsgGet::Parameters and returns Api::OneMe::Packets::Messaging::MsgGet::Response.
func (c *Client) SendMessagingMsgGet(req *MessagingMsgGetParameters) (*MessagingMsgGetResponse, error) {
	pkt, err := c.sendRaw(OpcodeMessagingMsgGet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*MessagingMsgGetResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp MessagingMsgGetResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendMessagingMsgGet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode72 sends Api::OneMe::Packets::Search::Message::Touch::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode72(req *SearchMessageTouchParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(72, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode72 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSearchMessage sends Api::OneMe::Packets::Search::Message::Parameters and returns Api::OneMe::Packets::Search::Message::Response.
func (c *Client) SendSearchMessage(req *SearchMessageParameters) (*SearchMessageResponse, error) {
	pkt, err := c.sendRaw(OpcodeSearchMessage, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SearchMessageResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SearchMessageResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSearchMessage raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatMsgGetStat sends Api::OneMe::Packets::Chat::MsgGetStat::Parameters and returns Api::OneMe::Packets::Chat::MsgGetStat::Response.
func (c *Client) SendChatMsgGetStat(req *ChatMsgGetStatParameters) (*ChatMsgGetStatResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatMsgGetStat, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatMsgGetStatResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatMsgGetStatResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatMsgGetStat raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode75 sends Api::OneMe::Packets::Chat::ChatSubscribe::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode75(req *ChatChatSubscribeParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(75, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode75 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsVideoChatStart sends Api::OneMe::Packets::Calls::VideoChatStart::Parameters and returns Api::OneMe::Packets::Calls::VideoChatStart::Response.
func (c *Client) SendCallsVideoChatStart(req *CallsVideoChatStartParameters) (*CallsVideoChatStartResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsVideoChatStart, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsVideoChatStartResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsVideoChatStartResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsVideoChatStart raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatMembersUpdate sends Api::OneMe::Packets::Chat::ChatMembersUpdate::Parameters and returns Api::OneMe::Packets::Chat::ChatMembersUpdate::Response.
func (c *Client) SendChatChatMembersUpdate(req *ChatChatMembersUpdateParameters) (*ChatChatMembersUpdateResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatMembersUpdate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatMembersUpdateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatMembersUpdateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatMembersUpdate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsVideoChatStartActive sends Api::OneMe::Packets::Calls::VideoChatStartActive::Parameters and returns Api::OneMe::Packets::Calls::VideoChatStartActive::Response.
func (c *Client) SendCallsVideoChatStartActive(req *CallsVideoChatStartActiveParameters) (*CallsVideoChatStartActiveResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsVideoChatStartActive, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsVideoChatStartActiveResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsVideoChatStartActiveResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsVideoChatStartActive raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsVideoChatHistory sends Api::OneMe::Packets::Calls::VideoChatHistory::Parameters and returns Api::OneMe::Packets::Calls::VideoChatHistory::Response.
func (c *Client) SendCallsVideoChatHistory(req *CallsVideoChatHistoryParameters) (*CallsVideoChatHistoryResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsVideoChatHistory, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsVideoChatHistoryResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsVideoChatHistoryResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsVideoChatHistory raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsPhotoUpload sends Api::OneMe::Packets::Attachments::PhotoUpload::Parameters and returns Api::OneMe::Packets::Attachments::PhotoUpload::Response.
func (c *Client) SendAttachmentsPhotoUpload(req *AttachmentsPhotoUploadParameters) (*AttachmentsPhotoUploadResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsPhotoUpload, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsPhotoUploadResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsPhotoUploadResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsPhotoUpload raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsVideoUpload sends Api::OneMe::Packets::Attachments::VideoUpload::Parameters and returns Api::OneMe::Packets::Attachments::VideoUpload::Response.
func (c *Client) SendAttachmentsVideoUpload(req *AttachmentsVideoUploadParameters) (*AttachmentsVideoUploadResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsVideoUpload, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsVideoUploadResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsVideoUploadResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsVideoUpload raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsVideoPlay sends Api::OneMe::Packets::Attachments::VideoPlay::Parameters and returns Api::OneMe::Packets::Attachments::VideoPlay::Response.
func (c *Client) SendAttachmentsVideoPlay(req *AttachmentsVideoPlayParameters) (*AttachmentsVideoPlayResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsVideoPlay, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsVideoPlayResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsVideoPlayResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsVideoPlay raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsVideoChatCreateJoinLink sends Api::OneMe::Packets::Calls::VideoChatCreateJoinLink::Parameters and returns Api::OneMe::Packets::Calls::VideoChatCreateJoinLink::Response.
func (c *Client) SendCallsVideoChatCreateJoinLink(req *CallsVideoChatCreateJoinLinkParameters) (*CallsVideoChatCreateJoinLinkResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsVideoChatCreateJoinLink, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsVideoChatCreateJoinLinkResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsVideoChatCreateJoinLinkResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsVideoChatCreateJoinLink raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatChatPinSetVisibility sends Api::OneMe::Packets::Chat::ChatPinSetVisibility::Parameters and returns Api::OneMe::Packets::Chat::ChatPinSetVisibility::Response.
func (c *Client) SendChatChatPinSetVisibility(req *ChatChatPinSetVisibilityParameters) (*ChatChatPinSetVisibilityResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatChatPinSetVisibility, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatChatPinSetVisibilityResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatChatPinSetVisibilityResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatChatPinSetVisibility raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsFileUpload sends Api::OneMe::Packets::Attachments::FileUpload::Parameters and returns Api::OneMe::Packets::Attachments::FileUpload::Response.
func (c *Client) SendAttachmentsFileUpload(req *AttachmentsFileUploadParameters) (*AttachmentsFileUploadResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsFileUpload, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsFileUploadResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsFileUploadResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsFileUpload raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsFileDownload sends Api::OneMe::Packets::Attachments::FileDownload::Parameters and returns Api::OneMe::Packets::Attachments::FileDownload::Response.
func (c *Client) SendAttachmentsFileDownload(req *AttachmentsFileDownloadParameters) (*AttachmentsFileDownloadResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsFileDownload, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsFileDownloadResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsFileDownloadResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsFileDownload raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendLinkInfo sends Api::OneMe::Packets::LinkInfo::Parameters and returns Api::OneMe::Packets::LinkInfo::Response.
func (c *Client) SendLinkInfo(req *LinkInfoParameters) (*LinkInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeLinkInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*LinkInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp LinkInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendLinkInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSessionsInfo sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::SessionsInfo::Response.
func (c *Client) SendSessionsInfo(req *EmptyParameters) (*SessionsInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeSessionsInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SessionsInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SessionsInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSessionsInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSessionsClose sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::SessionsClose::Response.
func (c *Client) SendSessionsClose(req *EmptyParameters) (*SessionsCloseResponse, error) {
	pkt, err := c.sendRaw(OpcodeSessionsClose, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SessionsCloseResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SessionsCloseResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSessionsClose raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeLoginRestorePassword sends Api::OneMe::Packets::Auth::OneMe::LoginRestorePassword::Parameters and returns Api::OneMe::Packets::Auth::OneMe::LoginRestorePassword::Response.
func (c *Client) SendAuthOneMeLoginRestorePassword(req *AuthOneMeLoginRestorePasswordParameters) (*AuthOneMeLoginRestorePasswordResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeLoginRestorePassword, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeLoginRestorePasswordResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeLoginRestorePasswordResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeLoginRestorePassword raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeDetails2FA sends Api::OneMe::Packets::Auth::OneMe::Details2FA::Parameters and returns Api::OneMe::Packets::Auth::OneMe::Details2FA::Response.
func (c *Client) SendAuthOneMeDetails2FA(req *AuthOneMeDetails2FAParameters) (*AuthOneMeDetails2FAResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeDetails2FA, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeDetails2FAResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeDetails2FAResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeDetails2FA raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendExternalCallback sends Api::OneMe::Packets::ExternalCallback::Parameters and returns Api::OneMe::Packets::ExternalCallback::Response.
func (c *Client) SendExternalCallback(req *ExternalCallbackParameters) (*ExternalCallbackResponse, error) {
	pkt, err := c.sendRaw(OpcodeExternalCallback, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ExternalCallbackResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ExternalCallbackResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendExternalCallback raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendWebAppWebAppRequestPhoneHash sends Api::OneMe::Packets::WebApp::WebAppRequestPhoneHash::Parameters and returns Api::OneMe::Packets::WebApp::WebAppRequestPhoneHash::Response.
func (c *Client) SendWebAppWebAppRequestPhoneHash(req *WebAppWebAppRequestPhoneHashParameters) (*WebAppWebAppRequestPhoneHashResponse, error) {
	pkt, err := c.sendRaw(OpcodeWebAppWebAppRequestPhoneHash, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*WebAppWebAppRequestPhoneHashResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp WebAppWebAppRequestPhoneHashResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendWebAppWebAppRequestPhoneHash raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode107 sends Api::OneMe::Packets::Auth::OneMe::ValidatePassword::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode107(req *AuthOneMeValidatePasswordParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(107, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode107 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode108 sends Api::OneMe::Packets::Auth::OneMe::ValidateHint::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode108(req *AuthOneMeValidateHintParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(108, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode108 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeVerifyEmail sends Api::OneMe::Packets::Auth::OneMe::VerifyEmail::Parameters and returns Api::OneMe::Packets::Auth::OneMe::VerifyEmail::Response.
func (c *Client) SendAuthOneMeVerifyEmail(req *AuthOneMeVerifyEmailParameters) (*AuthOneMeVerifyEmailResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeVerifyEmail, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeVerifyEmailResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeVerifyEmailResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeVerifyEmail raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeCheckEmail sends Api::OneMe::Packets::Auth::OneMe::CheckEmail::Parameters and returns Api::OneMe::Packets::Auth::OneMe::CheckEmail::Response.
func (c *Client) SendAuthOneMeCheckEmail(req *AuthOneMeCheckEmailParameters) (*AuthOneMeCheckEmailResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeCheckEmail, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeCheckEmailResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeCheckEmailResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeCheckEmail raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode111 sends Api::OneMe::Packets::Auth::OneMe::Set2FA::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode111(req *AuthOneMeSet2FAParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(111, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode111 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeCreateTrack sends Api::OneMe::Packets::Auth::OneMe::CreateTrack::Parameters and returns Api::OneMe::Packets::Auth::OneMe::CreateTrack::Response.
func (c *Client) SendAuthOneMeCreateTrack(req *AuthOneMeCreateTrackParameters) (*AuthOneMeCreateTrackResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeCreateTrack, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeCreateTrackResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeCreateTrackResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeCreateTrack raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeCheckPassword sends Api::OneMe::Packets::Auth::OneMe::CheckPassword::Parameters and returns Api::OneMe::Packets::Auth::OneMe::CheckPassword::Response.
func (c *Client) SendAuthOneMeCheckPassword(req *AuthOneMeCheckPasswordParameters) (*AuthOneMeCheckPasswordResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeCheckPassword, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeCheckPasswordResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeCheckPasswordResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeCheckPassword raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeLoginCheckPassword sends Api::OneMe::Packets::Auth::OneMe::LoginCheckPassword::Parameters and returns Api::OneMe::Packets::Auth::OneMe::LoginCheckPassword::Response.
func (c *Client) SendAuthOneMeLoginCheckPassword(req *AuthOneMeLoginCheckPasswordParameters) (*AuthOneMeLoginCheckPasswordResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeLoginCheckPassword, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeLoginCheckPasswordResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeLoginCheckPasswordResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeLoginCheckPassword raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeLoginProfileDelete sends Api::OneMe::Packets::Auth::OneMe::LoginProfileDelete::Parameters and returns Api::OneMe::Packets::Auth::OneMe::LoginProfileDelete::Response.
func (c *Client) SendAuthOneMeLoginProfileDelete(req *AuthOneMeLoginProfileDeleteParameters) (*AuthOneMeLoginProfileDeleteResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeLoginProfileDelete, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeLoginProfileDeleteResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeLoginProfileDeleteResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeLoginProfileDelete raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendMessagingSendCallback sends Api::OneMe::Packets::Messaging::SendCallback::Parameters and returns Api::OneMe::Packets::Messaging::SendCallback::Response.
func (c *Client) SendMessagingSendCallback(req *MessagingSendCallbackParameters) (*MessagingSendCallbackResponse, error) {
	pkt, err := c.sendRaw(OpcodeMessagingSendCallback, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*MessagingSendCallbackResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp MessagingSendCallbackResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendMessagingSendCallback raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode119 sends Api::OneMe::Packets::Bot::Suspend::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode119(req *BotSuspendParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(119, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode119 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendBotBotInfo sends Api::OneMe::Packets::Bot::BotInfo::Parameters and returns Api::OneMe::Packets::Bot::BotInfo::Response.
func (c *Client) SendBotBotInfo(req *BotBotInfoParameters) (*BotBotInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeBotBotInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*BotBotInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp BotBotInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendBotBotInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsCallsToken sends Api::OneMe::Packets::Calls::CallsToken::Parameters and returns Api::OneMe::Packets::Calls::CallsToken::Response.
func (c *Client) SendCallsCallsToken(req *CallsCallsTokenParameters) (*CallsCallsTokenResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsCallsToken, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsCallsTokenResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsCallsTokenResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsCallsToken raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendWebAppWebAppInitData sends Api::OneMe::Packets::WebApp::WebAppInitData::Parameters and returns Api::OneMe::Packets::WebApp::WebAppInitData::Response.
func (c *Client) SendWebAppWebAppInitData(req *WebAppWebAppInitDataParameters) (*WebAppWebAppInitDataResponse, error) {
	pkt, err := c.sendRaw(OpcodeWebAppWebAppInitData, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*WebAppWebAppInitDataResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp WebAppWebAppInitDataResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendWebAppWebAppInitData raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOpcode161 sends Api::OneMe::Packets::Complain::Parameters and returns Api::OneMe::Packets::EmptyResponse.
func (c *Client) SendOpcode161(req *ComplainParameters) (*EmptyResponse, error) {
	pkt, err := c.sendRaw(161, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*EmptyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp EmptyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOpcode161 raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendComplainReasonsGet sends Api::OneMe::Packets::ComplainReasonsGet::Parameters and returns Api::OneMe::Packets::ComplainReasonsGet::Response.
func (c *Client) SendComplainReasonsGet(req *ComplainReasonsGetParameters) (*ComplainReasonsGetResponse, error) {
	pkt, err := c.sendRaw(OpcodeComplainReasonsGet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ComplainReasonsGetResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ComplainReasonsGetResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendComplainReasonsGet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendCallsVideoChatJoin sends Api::OneMe::Packets::Calls::VideoChatJoin::Parameters and returns Api::OneMe::Packets::Calls::VideoChatJoin::Response.
func (c *Client) SendCallsVideoChatJoin(req *CallsVideoChatJoinParameters) (*CallsVideoChatJoinResponse, error) {
	pkt, err := c.sendRaw(OpcodeCallsVideoChatJoin, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*CallsVideoChatJoinResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp CallsVideoChatJoinResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendCallsVideoChatJoin raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsMsgReact sends Api::OneMe::Packets::Reactions::MsgReact::Parameters and returns Api::OneMe::Packets::Reactions::MsgReact::Response.
func (c *Client) SendReactionsMsgReact(req *ReactionsMsgReactParameters) (*ReactionsMsgReactResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsMsgReact, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsMsgReactResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsMsgReactResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsMsgReact raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsCancelReaction sends Api::OneMe::Packets::Reactions::CancelReaction::Parameters and returns Api::OneMe::Packets::Reactions::CancelReaction::Response.
func (c *Client) SendReactionsCancelReaction(req *ReactionsCancelReactionParameters) (*ReactionsCancelReactionResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsCancelReaction, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsCancelReactionResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsCancelReactionResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsCancelReaction raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsGetReactions sends Api::OneMe::Packets::Reactions::GetReactions::Parameters and returns Api::OneMe::Packets::Reactions::GetReactions::Response.
func (c *Client) SendReactionsGetReactions(req *ReactionsGetReactionsParameters) (*ReactionsGetReactionsResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsGetReactions, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsGetReactionsResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsGetReactionsResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsGetReactions raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsGetDetailedReactions sends Api::OneMe::Packets::Reactions::GetDetailedReactions::Parameters and returns Api::OneMe::Packets::Reactions::GetDetailedReactions::Response.
func (c *Client) SendReactionsGetDetailedReactions(req *ReactionsGetDetailedReactionsParameters) (*ReactionsGetDetailedReactionsResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsGetDetailedReactions, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsGetDetailedReactionsResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsGetDetailedReactionsResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsGetDetailedReactions raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendChatCommonChatList sends Api::OneMe::Packets::Chat::CommonChatList::Parameters and returns Api::OneMe::Packets::Chat::CommonChatList::Response.
func (c *Client) SendChatCommonChatList(req *ChatCommonChatListParameters) (*ChatCommonChatListResponse, error) {
	pkt, err := c.sendRaw(OpcodeChatCommonChatList, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ChatCommonChatListResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ChatCommonChatListResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendChatCommonChatList raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendProfileDelete sends Api::OneMe::Packets::ProfileDelete::Parameters and returns Api::OneMe::Packets::ProfileDelete::Response.
func (c *Client) SendProfileDelete(req *ProfileDeleteParameters) (*ProfileDeleteResponse, error) {
	pkt, err := c.sendRaw(OpcodeProfileDelete, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ProfileDeleteResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ProfileDeleteResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendProfileDelete raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendGetDeleteTamUserTime sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::GetDeleteTamUserTime::Response.
func (c *Client) SendGetDeleteTamUserTime(req *EmptyParameters) (*GetDeleteTamUserTimeResponse, error) {
	pkt, err := c.sendRaw(OpcodeGetDeleteTamUserTime, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*GetDeleteTamUserTimeResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp GetDeleteTamUserTimeResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendGetDeleteTamUserTime raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendTranscribeMedia sends Api::OneMe::Packets::TranscribeMedia::Parameters and returns Api::OneMe::Packets::TranscribeMedia::Response.
func (c *Client) SendTranscribeMedia(req *TranscribeMediaParameters) (*TranscribeMediaResponse, error) {
	pkt, err := c.sendRaw(OpcodeTranscribeMedia, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*TranscribeMediaResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp TranscribeMediaResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendTranscribeMedia raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendOrgInfo sends Api::OneMe::Packets::OrgInfo::Parameters and returns Api::OneMe::Packets::OrgInfo::Response.
func (c *Client) SendOrgInfo(req *OrgInfoParameters) (*OrgInfoResponse, error) {
	pkt, err := c.sendRaw(OpcodeOrgInfo, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*OrgInfoResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp OrgInfoResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendOrgInfo raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsSetChatReactions sends Api::OneMe::Packets::Reactions::SetChatReactions::Parameters and returns Api::OneMe::Packets::Reactions::SetChatReactions::Response.
func (c *Client) SendReactionsSetChatReactions(req *ReactionsSetChatReactionsParameters) (*ReactionsSetChatReactionsResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsSetChatReactions, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsSetChatReactionsResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsSetChatReactionsResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsSetChatReactions raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendReactionsGetChatReactions sends Api::OneMe::Packets::Reactions::GetChatReactions::Parameters and returns Api::OneMe::Packets::Reactions::GetChatReactions::Response.
func (c *Client) SendReactionsGetChatReactions(req *ReactionsGetChatReactionsParameters) (*ReactionsGetChatReactionsResponse, error) {
	pkt, err := c.sendRaw(OpcodeReactionsGetChatReactions, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*ReactionsGetChatReactionsResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp ReactionsGetChatReactionsResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendReactionsGetChatReactions raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsRemove sends Api::OneMe::Packets::Assets::Remove::Parameters and returns Api::OneMe::Packets::Assets::Remove::Response.
func (c *Client) SendAssetsRemove(req *AssetsRemoveParameters) (*AssetsRemoveResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsRemove, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsRemoveResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsRemoveResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsRemove raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAssetsListModify sends Api::OneMe::Packets::Assets::ListModify::Parameters and returns Api::OneMe::Packets::Assets::ListModify::Response.
func (c *Client) SendAssetsListModify(req *AssetsListModifyParameters) (*AssetsListModifyResponse, error) {
	pkt, err := c.sendRaw(OpcodeAssetsListModify, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AssetsListModifyResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AssetsListModifyResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAssetsListModify raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendFoldersGet sends Api::OneMe::Packets::Folders::Get::Parameters and returns Api::OneMe::Packets::Folders::Get::Response.
func (c *Client) SendFoldersGet(req *FoldersGetParameters) (*FoldersGetResponse, error) {
	pkt, err := c.sendRaw(OpcodeFoldersGet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*FoldersGetResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp FoldersGetResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendFoldersGet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendFoldersUpdate sends Api::OneMe::Packets::Folders::Update::Parameters and returns Api::OneMe::Packets::Folders::Update::Response.
func (c *Client) SendFoldersUpdate(req *FoldersUpdateParameters) (*FoldersUpdateResponse, error) {
	pkt, err := c.sendRaw(OpcodeFoldersUpdate, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*FoldersUpdateResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp FoldersUpdateResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendFoldersUpdate raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendFoldersReorder sends Api::OneMe::Packets::Folders::Reorder::Parameters and returns Api::OneMe::Packets::Folders::Reorder::Response.
func (c *Client) SendFoldersReorder(req *FoldersReorderParameters) (*FoldersReorderResponse, error) {
	pkt, err := c.sendRaw(OpcodeFoldersReorder, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*FoldersReorderResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp FoldersReorderResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendFoldersReorder raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendFoldersDelete sends Api::OneMe::Packets::Folders::Delete::Parameters and returns Api::OneMe::Packets::Folders::Delete::Response.
func (c *Client) SendFoldersDelete(req *FoldersDeleteParameters) (*FoldersDeleteResponse, error) {
	pkt, err := c.sendRaw(OpcodeFoldersDelete, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*FoldersDeleteResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp FoldersDeleteResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendFoldersDelete raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeCreateQr sends Api::OneMe::Packets::EmptyParameters and returns Api::OneMe::Packets::Auth::OneMe::CreateQr::Response.
func (c *Client) SendAuthOneMeCreateQr(req *EmptyParameters) (*AuthOneMeCreateQrResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeCreateQr, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeCreateQrResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeCreateQrResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeCreateQr raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeAuthCheck sends Api::OneMe::Packets::Auth::OneMe::AuthCheck::Parameters and returns Api::OneMe::Packets::Auth::OneMe::AuthCheck::Response.
func (c *Client) SendAuthOneMeAuthCheck(req *AuthOneMeAuthCheckParameters) (*AuthOneMeAuthCheckResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeAuthCheck, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeAuthCheckResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeAuthCheckResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeAuthCheck raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAuthOneMeAuthByTrack sends Api::OneMe::Packets::Auth::OneMe::AuthByTrack::Parameters and returns Api::OneMe::Packets::Auth::OneMe::AuthByTrack::Response.
func (c *Client) SendAuthOneMeAuthByTrack(req *AuthOneMeAuthByTrackParameters) (*AuthOneMeAuthByTrackResponse, error) {
	pkt, err := c.sendRaw(OpcodeAuthOneMeAuthByTrack, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AuthOneMeAuthByTrackResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AuthOneMeAuthByTrackResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAuthOneMeAuthByTrack raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendSuggestChatSuggest sends Api::OneMe::Packets::Suggest::ChatSuggest::Parameters and returns Api::OneMe::Packets::Suggest::ChatSuggest::Response.
func (c *Client) SendSuggestChatSuggest(req *SuggestChatSuggestParameters) (*SuggestChatSuggestResponse, error) {
	pkt, err := c.sendRaw(OpcodeSuggestChatSuggest, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*SuggestChatSuggestResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp SuggestChatSuggestResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendSuggestChatSuggest raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendAttachmentsAudioPlay sends Api::OneMe::Packets::Attachments::AudioPlay::Parameters and returns Api::OneMe::Packets::Attachments::AudioPlay::Response.
func (c *Client) SendAttachmentsAudioPlay(req *AttachmentsAudioPlayParameters) (*AttachmentsAudioPlayResponse, error) {
	pkt, err := c.sendRaw(OpcodeAttachmentsAudioPlay, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*AttachmentsAudioPlayResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp AttachmentsAudioPlayResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendAttachmentsAudioPlay raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendBannersBannersGet sends Api::OneMe::Packets::Banners::BannersGet::Parameters and returns Api::OneMe::Packets::Banners::BannersGet::Payload.
func (c *Client) SendBannersBannersGet(req *BannersBannersGetParameters) (*BannersBannersGetPayload, error) {
	pkt, err := c.sendRaw(OpcodeBannersBannersGet, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*BannersBannersGetPayload)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp BannersBannersGetPayload
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendBannersBannersGet raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendPollsSendVote sends Api::OneMe::Packets::Polls::SendVote::Parameters and returns Api::OneMe::Packets::Polls::SendVote::Response.
func (c *Client) SendPollsSendVote(req *PollsSendVoteParameters) (*PollsSendVoteResponse, error) {
	pkt, err := c.sendRaw(OpcodePollsSendVote, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*PollsSendVoteResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp PollsSendVoteResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendPollsSendVote raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendPollsVotersListByAnswer sends Api::OneMe::Packets::Polls::VotersListByAnswer::Parameters and returns Api::OneMe::Packets::Polls::VotersListByAnswer::Response.
func (c *Client) SendPollsVotersListByAnswer(req *PollsVotersListByAnswerParameters) (*PollsVotersListByAnswerResponse, error) {
	pkt, err := c.sendRaw(OpcodePollsVotersListByAnswer, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*PollsVotersListByAnswerResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp PollsVotersListByAnswerResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendPollsVotersListByAnswer raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

// SendPollsGetPollUpdates sends Api::OneMe::Packets::Polls::GetPollUpdates::Parameters and returns Api::OneMe::Packets::Polls::GetPollUpdates::Response.
func (c *Client) SendPollsGetPollUpdates(req *PollsGetPollUpdatesParameters) (*PollsGetPollUpdatesResponse, error) {
	pkt, err := c.sendRaw(OpcodePollsGetPollUpdates, req)
	if err != nil {
		return nil, err
	}
	resp, ok := pkt.Payload.(*PollsGetPollUpdatesResponse)
	if ok {
		return resp, nil
	}
	if len(pkt.RawPayload) > 0 {
		var resp PollsGetPollUpdatesResponse
		if err := msgpack.Unmarshal(pkt.RawPayload, &resp); err == nil {
			return &resp, nil
		} else {
			log.Printf("SendPollsGetPollUpdates raw unmarshal failed: %v", err)
		}
	}
	return nil, fmt.Errorf("invalid response type: %T", pkt.Payload)
}

func (c *Client) OnEventsNotificationCallAcceptedData(handler func(*EventsNotificationCallAcceptedDataResponse)) {
	c.On(OpcodeEventsNotificationCallAcceptedData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationCallAcceptedDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationCallAcceptedDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationCallAcceptedData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationCallFinishData(handler func(*EventsNotificationCallFinishDataResponse)) {
	c.On(OpcodeEventsNotificationCallFinishData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationCallFinishDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationCallFinishDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationCallFinishData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationMessageData(handler func(*EventsNotificationMessageDataPayload)) {
	c.On(OpcodeEventsNotificationMessageData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationMessageDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationMessageDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationMessageData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsTypingData(handler func(*EventsTypingDataPayload)) {
	c.On(OpcodeEventsTypingData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsTypingDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsTypingDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsTypingData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationMarkData(handler func(*EventsNotificationMarkDataResponse)) {
	c.On(OpcodeEventsNotificationMarkData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationMarkDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationMarkDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationMarkData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationContactData(handler func(*EventsNotificationContactDataResponse)) {
	c.On(OpcodeEventsNotificationContactData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationContactDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationContactDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationContactData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsPresenceNotificationMessageData(handler func(*EventsPresenceNotificationMessageDataPayload)) {
	c.On(OpcodeEventsPresenceNotificationMessageData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsPresenceNotificationMessageDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsPresenceNotificationMessageDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsPresenceNotificationMessageData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsConfigChangeData(handler func(*EventsConfigChangeDataPayload)) {
	c.On(OpcodeEventsConfigChangeData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsConfigChangeDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsConfigChangeDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsConfigChangeData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationChatData(handler func(*EventsNotificationChatDataResponse)) {
	c.On(OpcodeEventsNotificationChatData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationChatDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationChatDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationChatData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationAttachData(handler func(*EventsNotificationAttachDataResponse)) {
	c.On(OpcodeEventsNotificationAttachData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationAttachDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationAttachDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationAttachData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnOpcode137(handler func(*IncomingCall)) {
	c.On(137, func(p *Packet) {
		if v, ok := p.Payload.(*IncomingCall); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v IncomingCall
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnOpcode137 raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsMessagesDeleteRangeData(handler func(*EventsMessagesDeleteRangeDataResponse)) {
	c.On(OpcodeEventsMessagesDeleteRangeData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsMessagesDeleteRangeDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsMessagesDeleteRangeDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsMessagesDeleteRangeData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsMessagesDeleteData(handler func(*EventsMessagesDeleteDataResponse)) {
	c.On(OpcodeEventsMessagesDeleteData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsMessagesDeleteDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsMessagesDeleteDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsMessagesDeleteData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnAssets(handler func(*AssetsUpdateContent)) {
	c.On(OpcodeAssets, func(p *Packet) {
		if v, ok := p.Payload.(*AssetsUpdateContent); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v AssetsUpdateContent
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnAssets raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationMessageDelayedData(handler func(*EventsNotificationMessageDelayedDataPayload)) {
	c.On(OpcodeEventsNotificationMessageDelayedData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationMessageDelayedDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationMessageDelayedDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationMessageDelayedData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsReactionsChangedData(handler func(*EventsReactionsChangedDataResponse)) {
	c.On(OpcodeEventsReactionsChangedData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsReactionsChangedDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsReactionsChangedDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsReactionsChangedData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsYouReactedData(handler func(*EventsYouReactedDataResponse)) {
	c.On(OpcodeEventsYouReactedData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsYouReactedDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsYouReactedDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsYouReactedData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationProfiletData(handler func(*EventsNotificationProfiletDataResponse)) {
	c.On(OpcodeEventsNotificationProfiletData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationProfiletDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationProfiletDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationProfiletData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationFoldersData(handler func(*EventsNotificationFoldersDataResponse)) {
	c.On(OpcodeEventsNotificationFoldersData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationFoldersDataResponse); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationFoldersDataResponse
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationFoldersData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsBannersData(handler func(*EventsBannersDataPayload)) {
	c.On(OpcodeEventsBannersData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsBannersDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsBannersDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsBannersData raw unmarshal failed: %v", err)
			}
		}
	})
}

func (c *Client) OnEventsNotificationTranscriptionData(handler func(*EventsNotificationTranscriptionDataPayload)) {
	c.On(OpcodeEventsNotificationTranscriptionData, func(p *Packet) {
		if v, ok := p.Payload.(*EventsNotificationTranscriptionDataPayload); ok {
			handler(v)
			return
		}
		if len(p.RawPayload) > 0 {
			var v EventsNotificationTranscriptionDataPayload
			if err := msgpack.Unmarshal(p.RawPayload, &v); err == nil {
				handler(&v)
			} else {
				log.Printf("OnEventsNotificationTranscriptionData raw unmarshal failed: %v", err)
			}
		}
	})
}
