// Autogenerated. DO NOT EDIT

package main

import (
	"fmt"

	"github.com/vmihailenco/msgpack/v5"
)

// WidgetAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::WidgetAttachment
type WidgetAttachment struct {
	Type    string          `json:"_type" msgpack:"_type"`
	Deleted *bool           `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Message []WidgetContent `json:"message" msgpack:"message"`
}

// VideoAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::VideoAttachment
type VideoAttachment struct {
	Type                string        `json:"_type" msgpack:"_type"`
	Deleted             *bool         `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	VideoId             *int64        `json:"videoId,omitempty" msgpack:"videoId,omitempty"`
	VideoType           *int64        `json:"videoType,omitempty" msgpack:"videoType,omitempty"`
	Duration            *int16        `json:"duration,omitempty" msgpack:"duration,omitempty"`
	Thumbnail           *int64        `json:"thumbnail,omitempty" msgpack:"thumbnail,omitempty"`
	Width               *string       `json:"width,omitempty" msgpack:"width,omitempty"`
	Height              *int32        `json:"height,omitempty" msgpack:"height,omitempty"`
	EmbedUrl            *int32        `json:"embedUrl,omitempty" msgpack:"embedUrl,omitempty"`
	StartTime           *string       `json:"startTime,omitempty" msgpack:"startTime,omitempty"`
	ExternalUrl         *int64        `json:"externalUrl,omitempty" msgpack:"externalUrl,omitempty"`
	ExternalSiteName    *string       `json:"externalSiteName,omitempty" msgpack:"externalSiteName,omitempty"`
	PreviewData         *string       `json:"previewData,omitempty" msgpack:"previewData,omitempty"`
	Paid                *[]byte       `json:"paid,omitempty" msgpack:"paid,omitempty"`
	Token               *bool         `json:"token,omitempty" msgpack:"token,omitempty"`
	Collage             *string       `json:"collage,omitempty" msgpack:"collage,omitempty"`
	Transcription       *VideoCollage `json:"transcription,omitempty" msgpack:"transcription,omitempty"`
	TranscriptionStatus *string       `json:"transcriptionStatus,omitempty" msgpack:"transcriptionStatus,omitempty"`
	Wave                *string       `json:"wave,omitempty" msgpack:"wave,omitempty"`
	Thumbhash           *[]byte       `json:"thumbhash,omitempty" msgpack:"thumbhash,omitempty"`
}

// OutgoingPollAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::PollAttachment
type OutgoingPollAttachment struct {
	Type     string       `json:"_type" msgpack:"_type"`
	Deleted  *bool        `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	PollId   *int64       `json:"pollId,omitempty" msgpack:"pollId,omitempty"`
	Title    *int64       `json:"title,omitempty" msgpack:"title,omitempty"`
	Answers  string       `json:"answers" msgpack:"answers"`
	Settings []PollAnswer `json:"settings" msgpack:"settings"`
}

// UnsupportedAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::UnsupportedAttachment
type UnsupportedAttachment struct {
	Type                string `json:"_type" msgpack:"_type"`
	Deleted             *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	AttachmentConverter int64  `json:"AttachmentConverter" msgpack:"AttachmentConverter"`
}

// CallAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::CallAttachment
type CallAttachment struct {
	Type           string   `json:"_type" msgpack:"_type"`
	Deleted        *bool    `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	ConversationId string   `json:"conversationId" msgpack:"conversationId"`
	CallType       string   `json:"callType" msgpack:"callType"`
	HangupType     string   `json:"hangupType" msgpack:"hangupType"`
	Duration       *string  `json:"duration,omitempty" msgpack:"duration,omitempty"`
	ContactIds     *int32   `json:"contactIds,omitempty" msgpack:"contactIds,omitempty"`
	JoinLink       *[]int64 `json:"joinLink,omitempty" msgpack:"joinLink,omitempty"`
}

// FileAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::FileAttachment
type FileAttachment struct {
	Type    string `json:"_type" msgpack:"_type"`
	Deleted *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	FileId  int64  `json:"fileId" msgpack:"fileId"`
	Token   int64  `json:"token" msgpack:"token"`
	Size    string `json:"size,omitempty" msgpack:"size,omitempty"`
	Name    int64  `json:"name" msgpack:"name"`
	Preview string `json:"preview,omitempty" msgpack:"preview,omitempty"`
}

// PhotoAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::PhotoAttachment
type PhotoAttachment struct {
	Type        string  `json:"_type" msgpack:"_type"`
	Deleted     *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	PhotoId     *int64  `json:"photoId,omitempty" msgpack:"photoId,omitempty"`
	Url         *int64  `json:"url,omitempty" msgpack:"url,omitempty"`
	BaseUrl     *string `json:"baseUrl,omitempty" msgpack:"baseUrl,omitempty"`
	Width       *string `json:"width,omitempty" msgpack:"width,omitempty"`
	Height      *int32  `json:"height,omitempty" msgpack:"height,omitempty"`
	Gif         *int32  `json:"gif,omitempty" msgpack:"gif,omitempty"`
	PreviewData *bool   `json:"previewData,omitempty" msgpack:"previewData,omitempty"`
	Mp4Url      *[]byte `json:"mp4Url,omitempty" msgpack:"mp4Url,omitempty"`
	PhotoToken  *string `json:"photoToken,omitempty" msgpack:"photoToken,omitempty"`
	Sensitive   *string `json:"sensitive,omitempty" msgpack:"sensitive,omitempty"`
}

// ShareAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::ShareAttachment
type ShareAttachment struct {
	Type        string                   `json:"_type" msgpack:"_type"`
	Deleted     *bool                    `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	ShareId     int64                    `json:"shareId" msgpack:"shareId"`
	Url         int64                    `json:"url" msgpack:"url"`
	Title       *string                  `json:"title,omitempty" msgpack:"title,omitempty"`
	Description *string                  `json:"description,omitempty" msgpack:"description,omitempty"`
	Host        *string                  `json:"host,omitempty" msgpack:"host,omitempty"`
	Image       *string                  `json:"image,omitempty" msgpack:"image,omitempty"`
	Media       *PhotoAttachment         `json:"media,omitempty" msgpack:"media,omitempty"`
	IsSensitive *BaseAttachmentContainer `json:"isSensitive,omitempty" msgpack:"isSensitive,omitempty"`
}

// OutgoingFileAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::FileAttachment
type OutgoingFileAttachment struct {
	Type    string  `json:"_type" msgpack:"_type"`
	Deleted *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Token   *string `json:"token,omitempty" msgpack:"token,omitempty"`
}

// OutgoingShareAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::ShareAttachment
type OutgoingShareAttachment struct {
	Type    string `json:"_type" msgpack:"_type"`
	Deleted *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	ShareId int64  `json:"shareId" msgpack:"shareId"`
	Url     int64  `json:"url" msgpack:"url"`
}

// OutgoingPhotoAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::PhotoAttachment
type OutgoingPhotoAttachment struct {
	Type       string  `json:"_type" msgpack:"_type"`
	Deleted    *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	PhotoToken *string `json:"photoToken,omitempty" msgpack:"photoToken,omitempty"`
}

// ContactAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::ContactAttachment
type ContactAttachment struct {
	Type      string  `json:"_type" msgpack:"_type"`
	Deleted   *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	ContactId *int64  `json:"contactId,omitempty" msgpack:"contactId,omitempty"`
	FirstName *int64  `json:"firstName,omitempty" msgpack:"firstName,omitempty"`
	LastName  string  `json:"lastName,omitempty" msgpack:"lastName,omitempty"`
	PhotoUrl  *string `json:"photoUrl,omitempty" msgpack:"photoUrl,omitempty"`
	Phone     *string `json:"phone,omitempty" msgpack:"phone,omitempty"`
	VcfBody   *string `json:"vcfBody,omitempty" msgpack:"vcfBody,omitempty"`
}

// PollAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::PollAttachment
type PollAttachment struct {
	Type            string              `json:"_type" msgpack:"_type"`
	Deleted         *bool               `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	PollId          int64               `json:"pollId" msgpack:"pollId"`
	Title           int64               `json:"title" msgpack:"title"`
	Answers         string              `json:"answers" msgpack:"answers"`
	Settings        []PollAnswer        `json:"settings" msgpack:"settings"`
	State           int32               `json:"state" msgpack:"state"`
	Total           PollState           `json:"total" msgpack:"total"`
	Result          int32               `json:"result" msgpack:"result"`
	VoterPreviewIds *[]PollStateResults `json:"voterPreviewIds,omitempty" msgpack:"voterPreviewIds,omitempty"`
	Version         *[]int64            `json:"version,omitempty" msgpack:"version,omitempty"`
}

// AudioAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::AudioAttachment
type AudioAttachment struct {
	Type                string  `json:"_type" msgpack:"_type"`
	Deleted             *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	AudioId             int64   `json:"audioId" msgpack:"audioId"`
	Url                 int64   `json:"url" msgpack:"url"`
	Duration            *string `json:"duration,omitempty" msgpack:"duration,omitempty"`
	Wave                int32   `json:"wave" msgpack:"wave"`
	Transcription       *[]byte `json:"transcription,omitempty" msgpack:"transcription,omitempty"`
	TranscriptionStatus *string `json:"transcriptionStatus,omitempty" msgpack:"transcriptionStatus,omitempty"`
	Token               *string `json:"token,omitempty" msgpack:"token,omitempty"`
}

// ControlAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::ControlAttachment
type ControlAttachment struct {
	Type          string   `json:"_type" msgpack:"_type"`
	Deleted       *bool    `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Event         string   `json:"event" msgpack:"event"`
	UserIds       string   `json:"userIds" msgpack:"userIds"`
	Title         *[]int64 `json:"title,omitempty" msgpack:"title,omitempty"`
	Token         *string  `json:"token,omitempty" msgpack:"token,omitempty"`
	PhotoToken    *string  `json:"photoToken,omitempty" msgpack:"photoToken,omitempty"`
	Crop          *string  `json:"crop,omitempty" msgpack:"crop,omitempty"`
	UserId        *Crop    `json:"userId,omitempty" msgpack:"userId,omitempty"`
	Url           *int64   `json:"url,omitempty" msgpack:"url,omitempty"`
	FullUrl       *string  `json:"fullUrl,omitempty" msgpack:"fullUrl,omitempty"`
	Message       *string  `json:"message,omitempty" msgpack:"message,omitempty"`
	ShortMessage  *string  `json:"shortMessage,omitempty" msgpack:"shortMessage,omitempty"`
	ShowHistory   *string  `json:"showHistory,omitempty" msgpack:"showHistory,omitempty"`
	ChatType      *bool    `json:"chatType,omitempty" msgpack:"chatType,omitempty"`
	PinnedMessage *string  `json:"pinnedMessage,omitempty" msgpack:"pinnedMessage,omitempty"`
	StartPayload  *Message `json:"startPayload,omitempty" msgpack:"startPayload,omitempty"`
}

// OutgoingControlAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::ControlAttachment
type OutgoingControlAttachment struct {
	Type         string   `json:"_type" msgpack:"_type"`
	Deleted      *bool    `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Event        string   `json:"event" msgpack:"event"`
	ChatType     string   `json:"chatType" msgpack:"chatType"`
	Title        *string  `json:"title,omitempty" msgpack:"title,omitempty"`
	UserIds      *string  `json:"userIds,omitempty" msgpack:"userIds,omitempty"`
	StartPayload *[]int64 `json:"startPayload,omitempty" msgpack:"startPayload,omitempty"`
}

// LogSearchEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::SearchEventParams
type LogSearchEventParams struct {
	Type       string                       `json:"_type" msgpack:"_type"`
	Deleted    *bool                        `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	InputQuery LogSearchEventParamsSections `json:"inputQuery" msgpack:"inputQuery"`
	Sections   LogSearchEventParamsCounters `json:"sections" msgpack:"sections"`
	Counters   interface{}                  `json:"counters" msgpack:"counters"`
}

// LogLogEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::LogEventParams
type LogLogEventParams struct {
	Type    string `json:"_type" msgpack:"_type"`
	Deleted *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Msg     string `json:"msg" msgpack:"msg"`
	Details string `json:"details" msgpack:"details"`
}

// InlineKeyboardAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::InlineKeyboardAttachment
type InlineKeyboardAttachment struct {
	Type       string `json:"_type" msgpack:"_type"`
	Deleted    *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	CallbackId string `json:"callbackId" msgpack:"callbackId"`
	Keyboard   string `json:"keyboard" msgpack:"keyboard"`
}

// OutgoingStickerAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::StickerAttachment
type OutgoingStickerAttachment struct {
	Type      string `json:"_type" msgpack:"_type"`
	Deleted   *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	StickerId int64  `json:"stickerId" msgpack:"stickerId"`
}

// StickerAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::StickerAttachment
type StickerAttachment struct {
	Type        string    `json:"_type" msgpack:"_type"`
	Deleted     *bool     `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	StickerId   int64     `json:"stickerId" msgpack:"stickerId"`
	Width       int64     `json:"width" msgpack:"width"`
	Height      int32     `json:"height" msgpack:"height"`
	UpdateTime  int32     `json:"updateTime" msgpack:"updateTime"`
	Tags        *int64    `json:"tags,omitempty" msgpack:"tags,omitempty"`
	Url         *[]string `json:"url,omitempty" msgpack:"url,omitempty"`
	Mp4Url      string    `json:"mp4Url" msgpack:"mp4Url"`
	VideoUrl    *string   `json:"videoUrl,omitempty" msgpack:"videoUrl,omitempty"`
	FirstUrl    *string   `json:"firstUrl,omitempty" msgpack:"firstUrl,omitempty"`
	PreviewUrl  *string   `json:"previewUrl,omitempty" msgpack:"previewUrl,omitempty"`
	LottieUrl   *string   `json:"lottieUrl,omitempty" msgpack:"lottieUrl,omitempty"`
	Replies     *string   `json:"replies,omitempty" msgpack:"replies,omitempty"`
	SetId       *[]int64  `json:"setId,omitempty" msgpack:"setId,omitempty"`
	AuthorType  *int64    `json:"authorType,omitempty" msgpack:"authorType,omitempty"`
	StickerType *string   `json:"stickerType,omitempty" msgpack:"stickerType,omitempty"`
	Audio       *string   `json:"audio,omitempty" msgpack:"audio,omitempty"`
}

// OutgoingContactAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::ContactAttachment
type OutgoingContactAttachment struct {
	Type      string `json:"_type" msgpack:"_type"`
	Deleted   *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	ContactId int64  `json:"contactId" msgpack:"contactId"`
}

// ReplyKeyboardAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::ReplyKeyboardAttachment
type ReplyKeyboardAttachment struct {
	Type                 string          `json:"_type" msgpack:"_type"`
	Deleted              *bool           `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Keyboard             [][]ReplyButton `json:"keyboard" msgpack:"keyboard"`
	DefaultInputDisabled [][]ReplyButton `json:"defaultInputDisabled" msgpack:"defaultInputDisabled"`
}

// GeoPositionAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::GeoPositionAttachment
type GeoPositionAttachment struct {
	Type      string  `json:"_type" msgpack:"_type"`
	Deleted   *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Latitude  float32 `json:"latitude" msgpack:"latitude"`
	Longitude float32 `json:"longitude" msgpack:"longitude"`
	Zoom      float32 `json:"zoom" msgpack:"zoom"`
}

// OutgoingAudioAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::AudioAttachment
type OutgoingAudioAttachment struct {
	Type     string  `json:"_type" msgpack:"_type"`
	Deleted  *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Token    *string `json:"token,omitempty" msgpack:"token,omitempty"`
	Duration *string `json:"duration,omitempty" msgpack:"duration,omitempty"`
	Wave     *int32  `json:"wave,omitempty" msgpack:"wave,omitempty"`
}

// LogCallEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::CallEventParams
type LogCallEventParams struct {
	Type           string  `json:"_type" msgpack:"_type"`
	Deleted        *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Callid         *string `json:"call_id,omitempty" msgpack:"call_id,omitempty"`
	Isgroup        *string `json:"is_group,omitempty" msgpack:"is_group,omitempty"`
	Eventlabelstr  *bool   `json:"event_label_str,omitempty" msgpack:"event_label_str,omitempty"`
	Eventlabelint  *string `json:"event_label_int,omitempty" msgpack:"event_label_int,omitempty"`
	Customfeedback *int32  `json:"custom_feedback,omitempty" msgpack:"custom_feedback,omitempty"`
	Errortype      *string `json:"error_type,omitempty" msgpack:"error_type,omitempty"`
	Source         *string `json:"source,omitempty" msgpack:"source,omitempty"`
	Iswave         *string `json:"is_wave,omitempty" msgpack:"is_wave,omitempty"`
}

// LogNavEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::NavEventParams
type LogNavEventParams struct {
	Type       string `json:"_type" msgpack:"_type"`
	Deleted    *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Actionid   int64  `json:"action_id" msgpack:"action_id"`
	Screento   int64  `json:"screen_to" msgpack:"screen_to"`
	Prevtime   int32  `json:"prev_time" msgpack:"prev_time"`
	Screenfrom *int64 `json:"screen_from,omitempty" msgpack:"screen_from,omitempty"`
	Pip        *int32 `json:"pip,omitempty" msgpack:"pip,omitempty"`
	Reason     *int32 `json:"reason,omitempty" msgpack:"reason,omitempty"`
	Sourceid   *int32 `json:"source_id,omitempty" msgpack:"source_id,omitempty"`
	Sourcetype *int64 `json:"source_type,omitempty" msgpack:"source_type,omitempty"`
}

// OutgoingGeoPositionAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::GeoPositionAttachment
type OutgoingGeoPositionAttachment struct {
	Type      string  `json:"_type" msgpack:"_type"`
	Deleted   *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Latitude  float32 `json:"latitude" msgpack:"latitude"`
	Longitude float32 `json:"longitude" msgpack:"longitude"`
	Zoom      float32 `json:"zoom" msgpack:"zoom"`
}

// LogEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::EventParams
type LogEventParams struct {
	Type    string                                   `json:"_type" msgpack:"_type"`
	Deleted *bool                                    `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Field0  int64                                    `json:"field_0" msgpack:"field_0"`
	Field1  string                                   `json:"field_1" msgpack:"field_1"`
	Field2  *string                                  `json:"field_2,omitempty" msgpack:"field_2,omitempty"`
	Field3  *int64                                   `json:"field_3,omitempty" msgpack:"field_3,omitempty"`
	Field4  *int32                                   `json:"field_4,omitempty" msgpack:"field_4,omitempty"`
	Field5  *bool                                    `json:"field_5,omitempty" msgpack:"field_5,omitempty"`
	Field6  *[]int64                                 `json:"field_6,omitempty" msgpack:"field_6,omitempty"`
	Field7  int32                                    `json:"field_7" msgpack:"field_7"`
	Field8  LogEventParamsContainer                  `json:"field_8" msgpack:"field_8"`
	Field9  LogMessageSendProperties                 `json:"field_9" msgpack:"field_9"`
	Field10 []LogMessageSendSpan                     `json:"field_10" msgpack:"field_10"`
	Field11 []LogPermissionParams                    `json:"field_11" msgpack:"field_11"`
	Field12 *int8                                    `json:"field_12,omitempty" msgpack:"field_12,omitempty"`
	Field13 LogSearchEventParamsSections             `json:"field_13" msgpack:"field_13"`
	Field14 LogSearchEventParamsCounters             `json:"field_14" msgpack:"field_14"`
	Field15 *LogSettingsBackgroundAdditionallyParams `json:"field_15,omitempty" msgpack:"field_15,omitempty"`
	Field16 *LogSettingsThemeAdditionallyParams      `json:"field_16,omitempty" msgpack:"field_16,omitempty"`
}

// OutgoingVideoAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::VideoAttachment
type OutgoingVideoAttachment struct {
	Type      string  `json:"_type" msgpack:"_type"`
	Deleted   *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Token     *string `json:"token,omitempty" msgpack:"token,omitempty"`
	Duration  *string `json:"duration,omitempty" msgpack:"duration,omitempty"`
	Wave      *int32  `json:"wave,omitempty" msgpack:"wave,omitempty"`
	Thumbhash *[]byte `json:"thumbhash,omitempty" msgpack:"thumbhash,omitempty"`
}

// LogRegistrationEventParams is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Log::RegistrationEventParams
type LogRegistrationEventParams struct {
	Type         string  `json:"_type" msgpack:"_type"`
	Deleted      *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	Screen       *int32  `json:"screen,omitempty" msgpack:"screen,omitempty"`
	Reason       *int32  `json:"reason,omitempty" msgpack:"reason,omitempty"`
	Value        *int32  `json:"value,omitempty" msgpack:"value,omitempty"`
	PhoneCountry *int64  `json:"phoneCountry,omitempty" msgpack:"phoneCountry,omitempty"`
	Source       *string `json:"source,omitempty" msgpack:"source,omitempty"`
}

// AppAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::AppAttachment
type AppAttachment struct {
	Type    string  `json:"_type" msgpack:"_type"`
	Deleted *bool   `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
	AppId   int64   `json:"appId" msgpack:"appId"`
	Name    int64   `json:"name" msgpack:"name"`
	Icon    string  `json:"icon" msgpack:"icon"`
	Message *string `json:"message,omitempty" msgpack:"message,omitempty"`
	State   *string `json:"state,omitempty" msgpack:"state,omitempty"`
	Timeout *int32  `json:"timeout,omitempty" msgpack:"timeout,omitempty"`
}

// BaseAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::BaseAttachment
type BaseAttachment struct {
	Type    string `json:"_type" msgpack:"_type"`
	Deleted *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
}

// BaseAttachmentContainer is a container for the polymorphic type BaseAttachment.
// It stores the raw msgpack bytes and provides TryAs* methods for each known variant.
// Use the appropriate TryAs* method based on your application context
// (e.g. check a sibling _type field if available, or try each variant).
type BaseAttachmentContainer struct {
	raw []byte
	enc interface{}
}

// UnmarshalMsgpack captures raw bytes for deferred typed decoding.
func (c *BaseAttachmentContainer) UnmarshalMsgpack(data []byte) error {
	c.raw = make([]byte, len(data))
	copy(c.raw, data)
	return nil
}

// MarshalMsgpack serializes the container.
// If SetValue was called, serializes that value; otherwise re-serializes raw bytes.
func (c *BaseAttachmentContainer) MarshalMsgpack() ([]byte, error) {
	if c.enc != nil {
		return msgpack.Marshal(c.enc)
	}
	if c.raw != nil {
		return c.raw, nil
	}
	return nil, fmt.Errorf("BaseAttachmentContainer: no value to marshal")
}

// NewBaseAttachmentContainer creates a container wrapping a concrete variant value.
// Pass a pointer to any of the BaseAttachment variant structs.
func NewBaseAttachmentContainer(v interface{}) BaseAttachmentContainer {
	return BaseAttachmentContainer{enc: v}
}

// SetValue sets a concrete variant value for marshaling.
// Pass a pointer to any of the BaseAttachment variant structs.
func (c *BaseAttachmentContainer) SetValue(v interface{}) {
	c.enc = v
}

// RawBytes returns the raw msgpack bytes (for debugging or custom decoding).
func (c *BaseAttachmentContainer) RawBytes() []byte {
	return c.raw
}

// TryAsWidgetAttachment attempts to decode the container as WidgetAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsWidgetAttachment() (*WidgetAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsWidgetAttachment: no raw data")
	}
	var v WidgetAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsWidgetAttachment: %w", err)
	}
	return &v, nil
}

// TryAsVideoAttachment attempts to decode the container as VideoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsVideoAttachment() (*VideoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsVideoAttachment: no raw data")
	}
	var v VideoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsVideoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingPollAttachment attempts to decode the container as OutgoingPollAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingPollAttachment() (*OutgoingPollAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingPollAttachment: no raw data")
	}
	var v OutgoingPollAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingPollAttachment: %w", err)
	}
	return &v, nil
}

// TryAsUnsupportedAttachment attempts to decode the container as UnsupportedAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsUnsupportedAttachment() (*UnsupportedAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsUnsupportedAttachment: no raw data")
	}
	var v UnsupportedAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsUnsupportedAttachment: %w", err)
	}
	return &v, nil
}

// TryAsCallAttachment attempts to decode the container as CallAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsCallAttachment() (*CallAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsCallAttachment: no raw data")
	}
	var v CallAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsCallAttachment: %w", err)
	}
	return &v, nil
}

// TryAsFileAttachment attempts to decode the container as FileAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsFileAttachment() (*FileAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsFileAttachment: no raw data")
	}
	var v FileAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsFileAttachment: %w", err)
	}
	return &v, nil
}

// TryAsPhotoAttachment attempts to decode the container as PhotoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsPhotoAttachment() (*PhotoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsPhotoAttachment: no raw data")
	}
	var v PhotoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsPhotoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsShareAttachment attempts to decode the container as ShareAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsShareAttachment() (*ShareAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsShareAttachment: no raw data")
	}
	var v ShareAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsShareAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingFileAttachment attempts to decode the container as OutgoingFileAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingFileAttachment() (*OutgoingFileAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingFileAttachment: no raw data")
	}
	var v OutgoingFileAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingFileAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingShareAttachment attempts to decode the container as OutgoingShareAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingShareAttachment() (*OutgoingShareAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingShareAttachment: no raw data")
	}
	var v OutgoingShareAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingShareAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingPhotoAttachment attempts to decode the container as OutgoingPhotoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingPhotoAttachment() (*OutgoingPhotoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingPhotoAttachment: no raw data")
	}
	var v OutgoingPhotoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingPhotoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsContactAttachment attempts to decode the container as ContactAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsContactAttachment() (*ContactAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsContactAttachment: no raw data")
	}
	var v ContactAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsContactAttachment: %w", err)
	}
	return &v, nil
}

// TryAsPollAttachment attempts to decode the container as PollAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsPollAttachment() (*PollAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsPollAttachment: no raw data")
	}
	var v PollAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsPollAttachment: %w", err)
	}
	return &v, nil
}

// TryAsAudioAttachment attempts to decode the container as AudioAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsAudioAttachment() (*AudioAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsAudioAttachment: no raw data")
	}
	var v AudioAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsAudioAttachment: %w", err)
	}
	return &v, nil
}

// TryAsControlAttachment attempts to decode the container as ControlAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsControlAttachment() (*ControlAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsControlAttachment: no raw data")
	}
	var v ControlAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsControlAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingControlAttachment attempts to decode the container as OutgoingControlAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingControlAttachment() (*OutgoingControlAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingControlAttachment: no raw data")
	}
	var v OutgoingControlAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingControlAttachment: %w", err)
	}
	return &v, nil
}

// TryAsLogSearchEventParams attempts to decode the container as LogSearchEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogSearchEventParams() (*LogSearchEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogSearchEventParams: no raw data")
	}
	var v LogSearchEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogSearchEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogLogEventParams attempts to decode the container as LogLogEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogLogEventParams() (*LogLogEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogLogEventParams: no raw data")
	}
	var v LogLogEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogLogEventParams: %w", err)
	}
	return &v, nil
}

// TryAsInlineKeyboardAttachment attempts to decode the container as InlineKeyboardAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsInlineKeyboardAttachment() (*InlineKeyboardAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsInlineKeyboardAttachment: no raw data")
	}
	var v InlineKeyboardAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsInlineKeyboardAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingStickerAttachment attempts to decode the container as OutgoingStickerAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingStickerAttachment() (*OutgoingStickerAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingStickerAttachment: no raw data")
	}
	var v OutgoingStickerAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingStickerAttachment: %w", err)
	}
	return &v, nil
}

// TryAsStickerAttachment attempts to decode the container as StickerAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsStickerAttachment() (*StickerAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsStickerAttachment: no raw data")
	}
	var v StickerAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsStickerAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingContactAttachment attempts to decode the container as OutgoingContactAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingContactAttachment() (*OutgoingContactAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingContactAttachment: no raw data")
	}
	var v OutgoingContactAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingContactAttachment: %w", err)
	}
	return &v, nil
}

// TryAsReplyKeyboardAttachment attempts to decode the container as ReplyKeyboardAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsReplyKeyboardAttachment() (*ReplyKeyboardAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsReplyKeyboardAttachment: no raw data")
	}
	var v ReplyKeyboardAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsReplyKeyboardAttachment: %w", err)
	}
	return &v, nil
}

// TryAsGeoPositionAttachment attempts to decode the container as GeoPositionAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsGeoPositionAttachment() (*GeoPositionAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsGeoPositionAttachment: no raw data")
	}
	var v GeoPositionAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsGeoPositionAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingAudioAttachment attempts to decode the container as OutgoingAudioAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingAudioAttachment() (*OutgoingAudioAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingAudioAttachment: no raw data")
	}
	var v OutgoingAudioAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingAudioAttachment: %w", err)
	}
	return &v, nil
}

// TryAsLogCallEventParams attempts to decode the container as LogCallEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogCallEventParams() (*LogCallEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogCallEventParams: no raw data")
	}
	var v LogCallEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogCallEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogNavEventParams attempts to decode the container as LogNavEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogNavEventParams() (*LogNavEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogNavEventParams: no raw data")
	}
	var v LogNavEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogNavEventParams: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingGeoPositionAttachment attempts to decode the container as OutgoingGeoPositionAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingGeoPositionAttachment() (*OutgoingGeoPositionAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingGeoPositionAttachment: no raw data")
	}
	var v OutgoingGeoPositionAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingGeoPositionAttachment: %w", err)
	}
	return &v, nil
}

// TryAsLogEventParams attempts to decode the container as LogEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogEventParams() (*LogEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogEventParams: no raw data")
	}
	var v LogEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogEventParams: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingVideoAttachment attempts to decode the container as OutgoingVideoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsOutgoingVideoAttachment() (*OutgoingVideoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingVideoAttachment: no raw data")
	}
	var v OutgoingVideoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsOutgoingVideoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsLogRegistrationEventParams attempts to decode the container as LogRegistrationEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsLogRegistrationEventParams() (*LogRegistrationEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogRegistrationEventParams: no raw data")
	}
	var v LogRegistrationEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsLogRegistrationEventParams: %w", err)
	}
	return &v, nil
}

// TryAsAppAttachment attempts to decode the container as AppAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsAppAttachment() (*AppAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsAppAttachment: no raw data")
	}
	var v AppAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsAppAttachment: %w", err)
	}
	return &v, nil
}

// TryAsBaseAttachment attempts to decode the container as BaseAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *BaseAttachmentContainer) TryAsBaseAttachment() (*BaseAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsBaseAttachment: no raw data")
	}
	var v BaseAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("BaseAttachmentContainer.TryAsBaseAttachment: %w", err)
	}
	return &v, nil
}

// LogEventParamsContainer is a container for the polymorphic type EventParams.
// It stores the raw msgpack bytes and provides TryAs* methods for each known variant.
// Use the appropriate TryAs* method based on your application context
// (e.g. check a sibling _type field if available, or try each variant).
type LogEventParamsContainer struct {
	raw []byte
	enc interface{}
}

// UnmarshalMsgpack captures raw bytes for deferred typed decoding.
func (c *LogEventParamsContainer) UnmarshalMsgpack(data []byte) error {
	c.raw = make([]byte, len(data))
	copy(c.raw, data)
	return nil
}

// MarshalMsgpack serializes the container.
// If SetValue was called, serializes that value; otherwise re-serializes raw bytes.
func (c *LogEventParamsContainer) MarshalMsgpack() ([]byte, error) {
	if c.enc != nil {
		return msgpack.Marshal(c.enc)
	}
	if c.raw != nil {
		return c.raw, nil
	}
	return nil, fmt.Errorf("LogEventParamsContainer: no value to marshal")
}

// NewLogEventParamsContainer creates a container wrapping a concrete variant value.
// Pass a pointer to any of the EventParams variant structs.
func NewLogEventParamsContainer(v interface{}) LogEventParamsContainer {
	return LogEventParamsContainer{enc: v}
}

// SetValue sets a concrete variant value for marshaling.
// Pass a pointer to any of the EventParams variant structs.
func (c *LogEventParamsContainer) SetValue(v interface{}) {
	c.enc = v
}

// RawBytes returns the raw msgpack bytes (for debugging or custom decoding).
func (c *LogEventParamsContainer) RawBytes() []byte {
	return c.raw
}

// TryAsLogNavEventParams attempts to decode the container as LogNavEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogNavEventParams() (*LogNavEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogNavEventParams: no raw data")
	}
	var v LogNavEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogNavEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogRegistrationEventParams attempts to decode the container as LogRegistrationEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogRegistrationEventParams() (*LogRegistrationEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogRegistrationEventParams: no raw data")
	}
	var v LogRegistrationEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogRegistrationEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogSearchEventParams attempts to decode the container as LogSearchEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogSearchEventParams() (*LogSearchEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogSearchEventParams: no raw data")
	}
	var v LogSearchEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogSearchEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogCallEventParams attempts to decode the container as LogCallEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogCallEventParams() (*LogCallEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogCallEventParams: no raw data")
	}
	var v LogCallEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogCallEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogLogEventParams attempts to decode the container as LogLogEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogLogEventParams() (*LogLogEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogLogEventParams: no raw data")
	}
	var v LogLogEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogLogEventParams: %w", err)
	}
	return &v, nil
}

// TryAsLogEventParams attempts to decode the container as LogEventParams.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *LogEventParamsContainer) TryAsLogEventParams() (*LogEventParams, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogEventParams: no raw data")
	}
	var v LogEventParams
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("LogEventParamsContainer.TryAsLogEventParams: %w", err)
	}
	return &v, nil
}

// OutgoingBaseAttachment is a variant of a polymorphic type.
// Source: Api::OneMe::Types::Outgoing::BaseAttachment
type OutgoingBaseAttachment struct {
	Type    string `json:"_type" msgpack:"_type"`
	Deleted *bool  `json:"deleted,omitempty" msgpack:"deleted,omitempty"`
}

// OutgoingBaseAttachmentContainer is a container for the polymorphic type BaseAttachment.
// It stores the raw msgpack bytes and provides TryAs* methods for each known variant.
// Use the appropriate TryAs* method based on your application context
// (e.g. check a sibling _type field if available, or try each variant).
type OutgoingBaseAttachmentContainer struct {
	raw []byte
	enc interface{}
}

// UnmarshalMsgpack captures raw bytes for deferred typed decoding.
func (c *OutgoingBaseAttachmentContainer) UnmarshalMsgpack(data []byte) error {
	c.raw = make([]byte, len(data))
	copy(c.raw, data)
	return nil
}

// MarshalMsgpack serializes the container.
// If SetValue was called, serializes that value; otherwise re-serializes raw bytes.
func (c *OutgoingBaseAttachmentContainer) MarshalMsgpack() ([]byte, error) {
	if c.enc != nil {
		return msgpack.Marshal(c.enc)
	}
	if c.raw != nil {
		return c.raw, nil
	}
	return nil, fmt.Errorf("OutgoingBaseAttachmentContainer: no value to marshal")
}

// NewOutgoingBaseAttachmentContainer creates a container wrapping a concrete variant value.
// Pass a pointer to any of the BaseAttachment variant structs.
func NewOutgoingBaseAttachmentContainer(v interface{}) OutgoingBaseAttachmentContainer {
	return OutgoingBaseAttachmentContainer{enc: v}
}

// SetValue sets a concrete variant value for marshaling.
// Pass a pointer to any of the BaseAttachment variant structs.
func (c *OutgoingBaseAttachmentContainer) SetValue(v interface{}) {
	c.enc = v
}

// RawBytes returns the raw msgpack bytes (for debugging or custom decoding).
func (c *OutgoingBaseAttachmentContainer) RawBytes() []byte {
	return c.raw
}

// TryAsOutgoingControlAttachment attempts to decode the container as OutgoingControlAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingControlAttachment() (*OutgoingControlAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingControlAttachment: no raw data")
	}
	var v OutgoingControlAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingControlAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingVideoAttachment attempts to decode the container as OutgoingVideoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingVideoAttachment() (*OutgoingVideoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingVideoAttachment: no raw data")
	}
	var v OutgoingVideoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingVideoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingStickerAttachment attempts to decode the container as OutgoingStickerAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingStickerAttachment() (*OutgoingStickerAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingStickerAttachment: no raw data")
	}
	var v OutgoingStickerAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingStickerAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingPollAttachment attempts to decode the container as OutgoingPollAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingPollAttachment() (*OutgoingPollAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingPollAttachment: no raw data")
	}
	var v OutgoingPollAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingPollAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingContactAttachment attempts to decode the container as OutgoingContactAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingContactAttachment() (*OutgoingContactAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingContactAttachment: no raw data")
	}
	var v OutgoingContactAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingContactAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingFileAttachment attempts to decode the container as OutgoingFileAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingFileAttachment() (*OutgoingFileAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingFileAttachment: no raw data")
	}
	var v OutgoingFileAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingFileAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingShareAttachment attempts to decode the container as OutgoingShareAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingShareAttachment() (*OutgoingShareAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingShareAttachment: no raw data")
	}
	var v OutgoingShareAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingShareAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingPhotoAttachment attempts to decode the container as OutgoingPhotoAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingPhotoAttachment() (*OutgoingPhotoAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingPhotoAttachment: no raw data")
	}
	var v OutgoingPhotoAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingPhotoAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingAudioAttachment attempts to decode the container as OutgoingAudioAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingAudioAttachment() (*OutgoingAudioAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingAudioAttachment: no raw data")
	}
	var v OutgoingAudioAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingAudioAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingGeoPositionAttachment attempts to decode the container as OutgoingGeoPositionAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingGeoPositionAttachment() (*OutgoingGeoPositionAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingGeoPositionAttachment: no raw data")
	}
	var v OutgoingGeoPositionAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingGeoPositionAttachment: %w", err)
	}
	return &v, nil
}

// TryAsOutgoingBaseAttachment attempts to decode the container as OutgoingBaseAttachment.
// Returns an error if decoding fails — this does NOT guarantee the type is correct.
// Use contextual information (e.g. a _type field) to pick the right variant.
func (c *OutgoingBaseAttachmentContainer) TryAsOutgoingBaseAttachment() (*OutgoingBaseAttachment, error) {
	if c.raw == nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingBaseAttachment: no raw data")
	}
	var v OutgoingBaseAttachment
	if err := msgpack.Unmarshal(c.raw, &v); err != nil {
		return nil, fmt.Errorf("OutgoingBaseAttachmentContainer.TryAsOutgoingBaseAttachment: %w", err)
	}
	return &v, nil
}
