// Autogenerated. DO NOT EDIT

package main

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"log"

	lz4 "github.com/pierrec/lz4/v4"
	"github.com/vmihailenco/msgpack/v5"
)

const (
	ProtocolVersion     = 11
	MaxDecompressedSize = 8 * 1024 * 1024
)

// Packet represents a generic protocol packet.
type Packet struct {
	Ver        uint8       `json:"ver" msgpack:"ver"`
	Cmd        uint16      `json:"cmd" msgpack:"cmd"`
	Seq        uint8       `json:"seq" msgpack:"seq"`
	Opcode     uint16      `json:"opcode" msgpack:"opcode"`
	Payload    interface{} `json:"payload" msgpack:"payload"`
	RawPayload []byte      `json:"-" msgpack:"-"`
}

// opcodeResponseRegistry maps response opcodes to typed factory functions.
var opcodeResponseRegistry = map[uint16]func() interface{}{
	5:                                        func() interface{} { return &EmptyResponse{} },
	OpcodeSessionInit:                        func() interface{} { return &SessionInitResponse{} },
	OpcodeProfile:                            func() interface{} { return &ProfileResponse{} },
	OpcodeAuthOneMeAuthRequest:               func() interface{} { return &AuthOneMeAuthRequestResponse{} },
	OpcodeAuthOneMeAuth:                      func() interface{} { return &AuthOneMeAuthResponse{} },
	OpcodeAuthLogin:                          func() interface{} { return &AuthLoginResponse{} },
	20:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeConfig:                             func() interface{} { return &ConfigResponse{} },
	OpcodeAuthOneMeAuthConfirm:               func() interface{} { return &AuthOneMeAuthConfirmResponse{} },
	OpcodeAvatarPresetAvatar:                 func() interface{} { return &AvatarPresetAvatarResponse{} },
	OpcodeAssetsGetAssetStickerSet:           func() interface{} { return &AssetsGetAssetStickerSetResponse{} },
	OpcodeAssetsUpdate:                       func() interface{} { return &AssetsUpdateResponse{} },
	OpcodeAssetsGetByIdsAnimojiSet:           func() interface{} { return &AssetsGetByIdsAnimojiSetResponse{} },
	OpcodeAssetsAdd:                          func() interface{} { return &AssetsAddResponse{} },
	OpcodeContactContactInfo:                 func() interface{} { return &ContactContactInfoResponse{} },
	OpcodeContactContactUpdate:               func() interface{} { return &ContactContactUpdateResponse{} },
	OpcodeContactPresence:                    func() interface{} { return &ContactPresenceResponse{} },
	OpcodeContactContactList:                 func() interface{} { return &ContactContactListResponse{} },
	OpcodeSearchContact:                      func() interface{} { return &SearchContactResponse{} },
	OpcodeContactContactPhotos:               func() interface{} { return &ContactContactPhotosResponse{} },
	OpcodeContactContactCreate:               func() interface{} { return &ContactContactCreateResponse{} },
	OpcodeContactRemoveContactPhoto:          func() interface{} { return &ContactRemoveContactPhotoResponse{} },
	OpcodeContactContactByPhone:              func() interface{} { return &ContactContactByPhoneResponse{} },
	OpcodeChatChatInfo:                       func() interface{} { return &ChatChatInfoResponse{} },
	OpcodeChatChatHistory:                    func() interface{} { return &ChatChatHistoryResponse{} },
	OpcodeChatChatMark:                       func() interface{} { return &ChatChatMarkResponse{} },
	OpcodeChatChatMedia:                      func() interface{} { return &ChatChatMediaResponse{} },
	52:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeChatChatList:                       func() interface{} { return &ChatChatListResponse{} },
	54:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeChatChatUpdate:                     func() interface{} { return &ChatChatUpdateResponse{} },
	OpcodeChatCheckLink:                      func() interface{} { return &ChatCheckLinkResponse{} },
	OpcodeChatJoin:                           func() interface{} { return &ChatJoinResponse{} },
	OpcodeChatChatLeave:                      func() interface{} { return &ChatChatLeaveResponse{} },
	OpcodeChatChatMembers:                    func() interface{} { return &ChatChatMembersResponse{} },
	OpcodeSearchPublic:                       func() interface{} { return &SearchPublicResponse{} },
	OpcodeChatPersonalConfig:                 func() interface{} { return &ChatPersonalConfigResponse{} },
	OpcodeLiveStreamLiveStreamInfo:           func() interface{} { return &LiveStreamLiveStreamInfoResponse{} },
	OpcodeMessagingSend:                      func() interface{} { return &MessagingSendResponse{} },
	65:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeMessagingDelete:                    func() interface{} { return &MessagingDeleteResponse{} },
	OpcodeMessagingEdit:                      func() interface{} { return &MessagingEditResponse{} },
	OpcodeSearchChat:                         func() interface{} { return &SearchChatResponse{} },
	69:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeMessagingMsgGet:                    func() interface{} { return &MessagingMsgGetResponse{} },
	72:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeSearchMessage:                      func() interface{} { return &SearchMessageResponse{} },
	OpcodeChatMsgGetStat:                     func() interface{} { return &ChatMsgGetStatResponse{} },
	75:                                       func() interface{} { return &EmptyResponse{} },
	OpcodeCallsVideoChatStart:                func() interface{} { return &CallsVideoChatStartResponse{} },
	OpcodeChatChatMembersUpdate:              func() interface{} { return &ChatChatMembersUpdateResponse{} },
	OpcodeCallsVideoChatStartActive:          func() interface{} { return &CallsVideoChatStartActiveResponse{} },
	OpcodeCallsVideoChatHistory:              func() interface{} { return &CallsVideoChatHistoryResponse{} },
	OpcodeAttachmentsPhotoUpload:             func() interface{} { return &AttachmentsPhotoUploadResponse{} },
	OpcodeAttachmentsVideoUpload:             func() interface{} { return &AttachmentsVideoUploadResponse{} },
	OpcodeAttachmentsVideoPlay:               func() interface{} { return &AttachmentsVideoPlayResponse{} },
	OpcodeCallsVideoChatCreateJoinLink:       func() interface{} { return &CallsVideoChatCreateJoinLinkResponse{} },
	OpcodeChatChatPinSetVisibility:           func() interface{} { return &ChatChatPinSetVisibilityResponse{} },
	OpcodeAttachmentsFileUpload:              func() interface{} { return &AttachmentsFileUploadResponse{} },
	OpcodeAttachmentsFileDownload:            func() interface{} { return &AttachmentsFileDownloadResponse{} },
	OpcodeLinkInfo:                           func() interface{} { return &LinkInfoResponse{} },
	OpcodeSessionsInfo:                       func() interface{} { return &SessionsInfoResponse{} },
	OpcodeSessionsClose:                      func() interface{} { return &SessionsCloseResponse{} },
	OpcodeAuthOneMeLoginRestorePassword:      func() interface{} { return &AuthOneMeLoginRestorePasswordResponse{} },
	OpcodeAuthOneMeDetails2FA:                func() interface{} { return &AuthOneMeDetails2FAResponse{} },
	OpcodeExternalCallback:                   func() interface{} { return &ExternalCallbackResponse{} },
	OpcodeWebAppWebAppRequestPhoneHash:       func() interface{} { return &WebAppWebAppRequestPhoneHashResponse{} },
	107:                                      func() interface{} { return &EmptyResponse{} },
	108:                                      func() interface{} { return &EmptyResponse{} },
	OpcodeAuthOneMeVerifyEmail:               func() interface{} { return &AuthOneMeVerifyEmailResponse{} },
	OpcodeAuthOneMeCheckEmail:                func() interface{} { return &AuthOneMeCheckEmailResponse{} },
	111:                                      func() interface{} { return &EmptyResponse{} },
	OpcodeAuthOneMeCreateTrack:               func() interface{} { return &AuthOneMeCreateTrackResponse{} },
	OpcodeAuthOneMeCheckPassword:             func() interface{} { return &AuthOneMeCheckPasswordResponse{} },
	OpcodeAuthOneMeLoginCheckPassword:        func() interface{} { return &AuthOneMeLoginCheckPasswordResponse{} },
	OpcodeAuthOneMeLoginProfileDelete:        func() interface{} { return &AuthOneMeLoginProfileDeleteResponse{} },
	OpcodeMessagingSendCallback:              func() interface{} { return &MessagingSendCallbackResponse{} },
	119:                                      func() interface{} { return &EmptyResponse{} },
	OpcodeEventsNotificationCallAcceptedData: func() interface{} { return &EventsNotificationCallAcceptedDataResponse{} },
	OpcodeEventsNotificationCallFinishData:   func() interface{} { return &EventsNotificationCallFinishDataResponse{} },
	OpcodeEventsNotificationMessageData:      func() interface{} { return &EventsNotificationMessageDataPayload{} },
	OpcodeEventsTypingData:                   func() interface{} { return &EventsTypingDataPayload{} },
	OpcodeEventsNotificationMarkData:         func() interface{} { return &EventsNotificationMarkDataResponse{} },
	OpcodeEventsNotificationContactData:      func() interface{} { return &EventsNotificationContactDataResponse{} },
	OpcodeEventsPresenceNotificationMessageData: func() interface{} { return &EventsPresenceNotificationMessageDataPayload{} },
	OpcodeEventsConfigChangeData:                func() interface{} { return &EventsConfigChangeDataPayload{} },
	OpcodeEventsNotificationChatData:            func() interface{} { return &EventsNotificationChatDataResponse{} },
	OpcodeEventsNotificationAttachData:          func() interface{} { return &EventsNotificationAttachDataResponse{} },
	137:                                         func() interface{} { return &IncomingCall{} },
	OpcodeEventsMessagesDeleteRangeData:         func() interface{} { return &EventsMessagesDeleteRangeDataResponse{} },
	OpcodeEventsMessagesDeleteData:              func() interface{} { return &EventsMessagesDeleteDataResponse{} },
	OpcodeBotBotInfo:                            func() interface{} { return &BotBotInfoResponse{} },
	OpcodeAssets:                                func() interface{} { return &AssetsUpdateContent{} },
	OpcodeEventsNotificationMessageDelayedData:  func() interface{} { return &EventsNotificationMessageDelayedDataPayload{} },
	OpcodeEventsReactionsChangedData:            func() interface{} { return &EventsReactionsChangedDataResponse{} },
	OpcodeEventsYouReactedData:                  func() interface{} { return &EventsYouReactedDataResponse{} },
	OpcodeCallsCallsToken:                       func() interface{} { return &CallsCallsTokenResponse{} },
	OpcodeEventsNotificationProfiletData:        func() interface{} { return &EventsNotificationProfiletDataResponse{} },
	OpcodeWebAppWebAppInitData:                  func() interface{} { return &WebAppWebAppInitDataResponse{} },
	161:                                         func() interface{} { return &EmptyResponse{} },
	OpcodeComplainReasonsGet:                    func() interface{} { return &ComplainReasonsGetResponse{} },
	OpcodeCallsVideoChatJoin:                    func() interface{} { return &CallsVideoChatJoinResponse{} },
	OpcodeReactionsMsgReact:                     func() interface{} { return &ReactionsMsgReactResponse{} },
	OpcodeReactionsCancelReaction:               func() interface{} { return &ReactionsCancelReactionResponse{} },
	OpcodeReactionsGetReactions:                 func() interface{} { return &ReactionsGetReactionsResponse{} },
	OpcodeReactionsGetDetailedReactions:         func() interface{} { return &ReactionsGetDetailedReactionsResponse{} },
	OpcodeChatCommonChatList:                    func() interface{} { return &ChatCommonChatListResponse{} },
	OpcodeProfileDelete:                         func() interface{} { return &ProfileDeleteResponse{} },
	OpcodeGetDeleteTamUserTime:                  func() interface{} { return &GetDeleteTamUserTimeResponse{} },
	OpcodeTranscribeMedia:                       func() interface{} { return &TranscribeMediaResponse{} },
	OpcodeOrgInfo:                               func() interface{} { return &OrgInfoResponse{} },
	OpcodeReactionsSetChatReactions:             func() interface{} { return &ReactionsSetChatReactionsResponse{} },
	OpcodeReactionsGetChatReactions:             func() interface{} { return &ReactionsGetChatReactionsResponse{} },
	OpcodeAssetsRemove:                          func() interface{} { return &AssetsRemoveResponse{} },
	OpcodeAssetsListModify:                      func() interface{} { return &AssetsListModifyResponse{} },
	OpcodeFoldersGet:                            func() interface{} { return &FoldersGetResponse{} },
	OpcodeFoldersUpdate:                         func() interface{} { return &FoldersUpdateResponse{} },
	OpcodeFoldersReorder:                        func() interface{} { return &FoldersReorderResponse{} },
	OpcodeFoldersDelete:                         func() interface{} { return &FoldersDeleteResponse{} },
	OpcodeEventsNotificationFoldersData:         func() interface{} { return &EventsNotificationFoldersDataResponse{} },
	OpcodeAuthOneMeCreateQr:                     func() interface{} { return &AuthOneMeCreateQrResponse{} },
	OpcodeAuthOneMeAuthCheck:                    func() interface{} { return &AuthOneMeAuthCheckResponse{} },
	OpcodeAuthOneMeAuthByTrack:                  func() interface{} { return &AuthOneMeAuthByTrackResponse{} },
	OpcodeEventsBannersData:                     func() interface{} { return &EventsBannersDataPayload{} },
	OpcodeEventsNotificationTranscriptionData:   func() interface{} { return &EventsNotificationTranscriptionDataPayload{} },
	OpcodeSuggestChatSuggest:                    func() interface{} { return &SuggestChatSuggestResponse{} },
	OpcodeAttachmentsAudioPlay:                  func() interface{} { return &AttachmentsAudioPlayResponse{} },
	OpcodeBannersBannersGet:                     func() interface{} { return &BannersBannersGetPayload{} },
	OpcodePollsSendVote:                         func() interface{} { return &PollsSendVoteResponse{} },
	OpcodePollsVotersListByAnswer:               func() interface{} { return &PollsVotersListByAnswerResponse{} },
	OpcodePollsGetPollUpdates:                   func() interface{} { return &PollsGetPollUpdatesResponse{} },
}

// PackPacket packs a packet for TCP transport (msgpack + optional lz4 raw block).
func PackPacket(ver uint8, cmd uint16, seq uint8, opcode uint16, payload interface{}) ([]byte, error) {
	var buf bytes.Buffer
	enc := msgpack.NewEncoder(&buf)
	enc.SetCustomStructTag("msgpack")
	if err := enc.Encode(payload); err != nil {
		return nil, fmt.Errorf("msgpack encode payload: %w", err)
	}
	payloadBytes := buf.Bytes()

	compFlag := byte(0)
	if len(payloadBytes) > 4096 {
		dst := make([]byte, lz4.CompressBlockBound(len(payloadBytes)))
		n, err := lz4.CompressBlock(payloadBytes, dst, nil)
		if err != nil {
			return nil, fmt.Errorf("lz4 compress: %w", err)
		}
		payloadBytes = dst[:n]
		compFlag = 1
	}

	payloadLen := len(payloadBytes) & 0xFFFFFF
	packedLen := uint32(compFlag)<<24 | uint32(payloadLen)

	header := make([]byte, 10)
	header[0] = ver
	binary.BigEndian.PutUint16(header[1:3], cmd)
	header[3] = seq
	binary.BigEndian.PutUint16(header[4:6], opcode)
	binary.BigEndian.PutUint32(header[6:10], packedLen)
	return append(header, payloadBytes...), nil
}

// UnpackPacket unpacks a TCP packet.
func UnpackPacket(data []byte) (*Packet, error) {
	if len(data) < 10 {
		return nil, fmt.Errorf("packet too short: %d bytes", len(data))
	}
	ver := data[0]
	cmd := binary.BigEndian.Uint16(data[1:3])
	seq := data[3]
	opcode := binary.BigEndian.Uint16(data[4:6])
	packedLen := binary.BigEndian.Uint32(data[6:10])
	compFlag := packedLen >> 24
	payloadLen := int(packedLen & 0xFFFFFF)

	if len(data) < 10+payloadLen {
		return nil, fmt.Errorf("packet body incomplete: need %d, have %d", 10+payloadLen, len(data))
	}
	payloadBytes := data[10 : 10+payloadLen]

	if compFlag != 0 {
		decompressed := make([]byte, MaxDecompressedSize)
		n, err := lz4.UncompressBlock(payloadBytes, decompressed)
		if err != nil {
			return nil, fmt.Errorf("lz4 decompress: %w", err)
		}
		payloadBytes = decompressed[:n]
	}

	var payload interface{}
	if len(payloadBytes) > 0 {
		dec := msgpack.NewDecoder(bytes.NewReader(payloadBytes))
		dec.SetCustomStructTag("msgpack")
		if cmd != 3 {
			if factory, ok := opcodeResponseRegistry[opcode]; ok {
				payload = factory()
				if err := dec.Decode(payload); err != nil {
					log.Printf("typed decode failed opcode=%d len=%d hex=%s: %v, falling back", opcode, len(payloadBytes), hex.EncodeToString(payloadBytes), err)
					payload = nil
					dec = msgpack.NewDecoder(bytes.NewReader(payloadBytes))
					dec.SetCustomStructTag("msgpack")
					if err := dec.Decode(&payload); err != nil {
						log.Printf("fallback decode failed opcode=%d len=%d hex=%s: %v, returning nil payload", opcode, len(payloadBytes), hex.EncodeToString(payloadBytes), err)
					}
				}
			} else {
				if err := dec.Decode(&payload); err != nil {
					log.Printf("fallback decode failed opcode=%d len=%d hex=%s: %v, returning nil payload", opcode, len(payloadBytes), hex.EncodeToString(payloadBytes), err)
				}
			}
		} else {
			if err := dec.Decode(&payload); err != nil {
				log.Printf("fallback decode failed opcode=%d len=%d hex=%s: %v, returning nil payload", opcode, len(payloadBytes), hex.EncodeToString(payloadBytes), err)
			}
		}
	}

	return &Packet{Ver: ver, Cmd: cmd, Seq: seq, Opcode: opcode, Payload: payload, RawPayload: payloadBytes}, nil
}
